# SPDX-License-Identifier: MIT
# Independent native MTP mass/RNG/controller saved-data checks; NOT-INFERENCE.
cmake_minimum_required(VERSION 3.21)
if(EXISTS "${OUTPUT}")
  message(FATAL_ERROR "MTP replay fixture output must be new")
endif()
file(MAKE_DIRECTORY "${OUTPUT}")
foreach(mode IN ITEMS text tools boundary)
  set(args --model :fixture: --tokens 16 --draft-tokens 7)
  if(mode STREQUAL "tools")
    set(args --model :tools: --tokens 8 --draft-tokens 7 --tools)
  elseif(mode STREQUAL "boundary")
    set(args --model :fixture: --tokens 128 --draft-tokens 1)
  endif()
  # Positional model/output arguments retain the native client's AR contract.
  list(GET args 1 model)
  list(REMOVE_AT args 0 1)
  execute_process(COMMAND "${CAPTURE}" --model "${model}" --output-dir "${OUTPUT}/${mode}" ${args} --mtp-model :predictor:
    OUTPUT_FILE "${OUTPUT}/${mode}-capture.stdout" ERROR_FILE "${OUTPUT}/${mode}-capture.stderr" RESULT_VARIABLE rc TIMEOUT 30)
  file(WRITE "${OUTPUT}/${mode}-capture.exit" "${rc}\n")
  if(NOT rc STREQUAL "0")
    message(FATAL_ERROR "MTP ${mode} capture exit ${rc}; actual logs retained")
  endif()
  foreach(arm IN ITEMS REFERENCE CANDIDATE FALLBACK)
    execute_process(COMMAND "${${arm}}" --capture "${OUTPUT}/${mode}" --allow-synthetic
      OUTPUT_FILE "${OUTPUT}/${mode}-${arm}.txt" ERROR_FILE "${OUTPUT}/${mode}-${arm}.stderr" RESULT_VARIABLE rc TIMEOUT 30)
    file(WRITE "${OUTPUT}/${mode}-${arm}.exit" "${rc}\n")
    if(NOT rc STREQUAL "0")
      message(FATAL_ERROR "MTP ${mode} ${arm} replay exit ${rc}; actual logs retained")
    endif()
    file(SHA256 "${OUTPUT}/${mode}-${arm}.txt" ${arm}_hash)
  endforeach()
  if(NOT REFERENCE_hash STREQUAL CANDIDATE_hash OR NOT REFERENCE_hash STREQUAL FALLBACK_hash)
    message(FATAL_ERROR "Complete MTP target/proposal/residual/RNG/controller witnesses differ")
  endif()
  if(mode STREQUAL "text" OR mode STREQUAL "boundary")
    file(READ "${OUTPUT}/${mode}-REFERENCE.txt" witness)
    if(NOT witness MATCHES "PROPOSALS=[1-9][0-9]* ACCEPTED=[1-9][0-9]* REJECTED=[1-9][0-9]* DEFERRED=[1-9][0-9]* ")
      message(FATAL_ERROR "Synthetic MTP fixture must exercise acceptance, rejection and deferred correction")
    endif()
  endif()
endforeach()
file(READ "${OUTPUT}/text/capture.jsonl" original)
string(REGEX MATCH "\n\\{\"event\":\"sampling_trace\"[^\n]*\"kind\":\"target-draw\"[^\n]*\n" target_line "${original}")
string(REGEX MATCH "\n\\{\"event\":\"sampling_trace\"[^\n]*\"kind\":\"proposal\"[^\n]*\n" proposal_line "${original}")
string(REGEX MATCH "\n\\{\"event\":\"sampling_trace\"[^\n]*\"kind\":\"verification\"[^\n]*\n" verification_line "${original}")
string(REGEX MATCH "\n\\{\"event\":\"cycle_complete\"[^\n]*\n" cycle_line "${original}")
if(NOT target_line OR NOT proposal_line OR NOT verification_line OR NOT cycle_line)
  message(FATAL_ERROR "MTP fixture lacks required roles/frontiers")
endif()
foreach(case IN ITEMS synthetic raw-hash truncated path raw-fifo raw-symlink metadata-fifo terminal generation
    rng-before rng-after deferred history penalties proposal-mass proposal-token verification-accepted
    verification-rng cycle-frontier cycle-stop missing-cycle)
  set(destination "${OUTPUT}/bad-${case}")
  file(MAKE_DIRECTORY "${destination}")
  file(GLOB payloads "${OUTPUT}/text/*.f32le")
  file(COPY ${payloads} DESTINATION "${destination}")
  set(data "${original}")
  set(extra --allow-synthetic)
  set(changed "")
  set(selected "${target_line}")
  string(STRIP "${target_line}" row)
  if(case STREQUAL "synthetic")
    set(extra)
  elseif(case STREQUAL "raw-hash")
    string(REPEAT "0" 64 hash)
    string(JSON changed SET "${row}" raw sha256 "\"${hash}\"")
  elseif(case STREQUAL "truncated")
    file(WRITE "${destination}/profile-0-trace-0.f32le" "short")
  elseif(case STREQUAL "path")
    string(JSON changed SET "${row}" raw file "\"../profile-0-trace-0.f32le\"")
  elseif(case STREQUAL "terminal")
    string(REGEX REPLACE "\\{\"event\":\"complete\"[^\n]*\n?$" "" data "${data}")
  elseif(case STREQUAL "generation")
    string(REPLACE "\"seed\":123" "\"seed\":\"123\"" data "${data}")
  elseif(case STREQUAL "rng-before" OR case STREQUAL "rng-after")
    if(case STREQUAL "rng-before")
      set(key rng_before)
    else()
      set(key rng_after)
    endif()
    string(JSON changed SET "${row}" ${key} "\"0000000000000001\"")
  elseif(case STREQUAL "deferred")
    string(JSON changed SET "${row}" deferred 1)
  elseif(case STREQUAL "history")
    string(JSON changed SET "${row}" history_ids 0 1)
  elseif(case STREQUAL "penalties")
    string(JSON changed SET "${row}" penalties "[{\"token\":0,\"generated_count\":1,\"repeated\":0}]")
  elseif(case STREQUAL "proposal-mass" OR case STREQUAL "proposal-token")
    set(selected "${proposal_line}")
    string(STRIP "${selected}" row)
    if(case STREQUAL "proposal-mass")
      string(JSON changed SET "${row}" proposal probabilities 0 0.5)
    else()
      string(JSON token GET "${row}" proposal token)
      math(EXPR token "(${token}+1)%17")
      string(JSON changed SET "${row}" proposal token ${token})
    endif()
  elseif(case STREQUAL "verification-accepted" OR case STREQUAL "verification-rng")
    set(selected "${verification_line}")
    string(STRIP "${selected}" row)
    if(case STREQUAL "verification-accepted")
      string(JSON accepted GET "${row}" accepted)
      math(EXPR accepted "1-${accepted}")
      string(JSON changed SET "${row}" accepted ${accepted})
    else()
      string(JSON changed SET "${row}" rng_after "\"0000000000000001\"")
    endif()
  elseif(case STREQUAL "cycle-frontier" OR case STREQUAL "cycle-stop")
    set(selected "${cycle_line}")
    string(STRIP "${selected}" row)
    if(case STREQUAL "cycle-frontier")
      string(JSON position GET "${row}" position)
      math(EXPR position "${position}+1")
      string(JSON changed SET "${row}" position ${position})
    else()
      string(JSON changed SET "${row}" stop true)
    endif()
  elseif(case STREQUAL "missing-cycle")
    string(REPLACE "${cycle_line}" "\n" data "${data}")
  endif()
  if(changed)
    string(REPLACE "\n" "" changed "${changed}")
    string(REPLACE "${selected}" "\n${changed}\n" data "${data}")
  endif()
  file(WRITE "${destination}/capture.jsonl" "${data}")
  if(case STREQUAL "raw-fifo" OR case STREQUAL "raw-symlink" OR case STREQUAL "metadata-fifo")
    set(path "${destination}/profile-0-trace-0.f32le")
    if(case STREQUAL "metadata-fifo")
      set(path "${destination}/capture.jsonl")
    endif()
    file(REMOVE "${path}")
    if(case STREQUAL "raw-symlink")
      file(CREATE_LINK "../text/profile-0-trace-0.f32le" "${path}" SYMBOLIC)
    else()
      execute_process(COMMAND "${FILE_FIXTURE}" --fifo "${path}" RESULT_VARIABLE rc TIMEOUT 10)
      if(NOT rc STREQUAL "0")
        message(FATAL_ERROR "Owned MTP FIFO fixture creation failed: ${rc}")
      endif()
    endif()
  endif()
  execute_process(COMMAND "${CANDIDATE}" --capture "${destination}" ${extra}
    OUTPUT_FILE "${OUTPUT}/${case}.txt" ERROR_FILE "${OUTPUT}/${case}.stderr" RESULT_VARIABLE rc TIMEOUT 30)
  file(WRITE "${OUTPUT}/${case}.exit" "${rc}\n")
  if(NOT rc STREQUAL "1")
    message(FATAL_ERROR "MTP ${case} refusal exit ${rc}, expected actual exit 1")
  endif()
endforeach()
# A checksum-correct grammar mask corruption must still fail the byte-walk oracle.
file(READ "${OUTPUT}/tools/capture.jsonl" data)
file(MAKE_DIRECTORY "${OUTPUT}/bad-mask")
file(GLOB payloads "${OUTPUT}/tools/*.f32le" "${OUTPUT}/tools/*.u8" "${OUTPUT}/tools/*.bin")
file(COPY ${payloads} DESTINATION "${OUTPUT}/bad-mask")
file(SHA256 "${OUTPUT}/tools/profile-0-trace-0.u8" old_hash)
file(READ "${OUTPUT}/tools/profile-0-trace-1.u8" mask HEX)
file(COPY_FILE "${OUTPUT}/tools/profile-0-trace-1.u8" "${OUTPUT}/bad-mask/profile-0-trace-0.u8")
file(SHA256 "${OUTPUT}/bad-mask/profile-0-trace-0.u8" new_hash)
string(REPLACE "${old_hash}" "${new_hash}" data "${data}")
file(WRITE "${OUTPUT}/bad-mask/capture.jsonl" "${data}")
execute_process(COMMAND "${CANDIDATE}" --capture "${OUTPUT}/bad-mask" --allow-synthetic
  OUTPUT_FILE "${OUTPUT}/mask.txt" ERROR_FILE "${OUTPUT}/mask.stderr" RESULT_VARIABLE rc TIMEOUT 30)
file(WRITE "${OUTPUT}/mask.exit" "${rc}\n")
if(NOT rc STREQUAL "1")
  message(FATAL_ERROR "MTP independent mask refusal exit ${rc}, expected actual exit 1")
endif()
message(STATUS "MTP target/proposal/acceptance/residual/deferred/RNG/controller witnesses agree; 22 refusals pass; NOT-INFERENCE")
