# SPDX-License-Identifier: MIT
# Focused native captured-row/parser controls; no model, device or performance.
cmake_minimum_required(VERSION 3.21)
if(EXISTS "${OUTPUT}")
  message(FATAL_ERROR "Replay fixture output must be new")
endif()
file(MAKE_DIRECTORY "${OUTPUT}")
execute_process(COMMAND "${CAPTURE}" --model :fixture: --output-dir "${OUTPUT}/good" --tokens 8
  OUTPUT_FILE "${OUTPUT}/capture.stdout" ERROR_FILE "${OUTPUT}/capture.stderr" RESULT_VARIABLE rc TIMEOUT 30)
file(WRITE "${OUTPUT}/capture.exit" "${rc}\n")
if(NOT rc STREQUAL "0")
  message(FATAL_ERROR "Capture fixture failed: ${rc}")
endif()
foreach(arm IN ITEMS REFERENCE CANDIDATE FALLBACK)
  execute_process(COMMAND "${${arm}}" --capture "${OUTPUT}/good" --allow-synthetic
    OUTPUT_FILE "${OUTPUT}/${arm}.txt" ERROR_FILE "${OUTPUT}/${arm}.stderr" RESULT_VARIABLE rc TIMEOUT 30)
  file(WRITE "${OUTPUT}/${arm}.exit" "${rc}\n")
  if(NOT rc STREQUAL "0")
    message(FATAL_ERROR "${arm} replay fixture exit ${rc}; logs preserved")
  endif()
  file(SHA256 "${OUTPUT}/${arm}.txt" ${arm}_hash)
endforeach()
if(NOT REFERENCE_hash STREQUAL CANDIDATE_hash OR NOT REFERENCE_hash STREQUAL FALLBACK_hash)
  message(FATAL_ERROR "Complete captured-row mass/draw/residual witnesses differ")
endif()
file(READ "${OUTPUT}/good/capture.jsonl" original)
string(REGEX MATCH "\n\\{\"event\":\"row\"[^\n]*\n" first_row "${original}")
if(NOT first_row)
  message(FATAL_ERROR "Capture fixture first row missing")
endif()
string(STRIP "${first_row}" row_json)
string(JSON token GET "${row_json}" token)
math(EXPR different "(${token}+1)%17")
foreach(case IN ITEMS synthetic token SHA truncated terminal generation path row-fifo metadata-fifo)
  set(destination "${OUTPUT}/${case}")
  file(MAKE_DIRECTORY "${destination}")
  file(GLOB payloads "${OUTPUT}/good/*.f32le")
  file(COPY ${payloads} DESTINATION "${destination}")
  set(data "${original}")
  set(extra --allow-synthetic)
  if(case STREQUAL "synthetic")
    set(extra)
  elseif(case STREQUAL "token")
    string(REGEX REPLACE "\"token\":[0-9]+" "\"token\":${different}" bad "${first_row}")
    string(REPLACE "${first_row}" "${bad}" data "${data}")
  elseif(case STREQUAL "SHA")
    configure_file("${OUTPUT}/good/profile-0-row-1.f32le"
      "${destination}/profile-0-row-0.f32le" COPYONLY)
  elseif(case STREQUAL "truncated")
    file(WRITE "${destination}/profile-0-row-0.f32le" "short")
  elseif(case STREQUAL "terminal")
    string(REGEX REPLACE "\\{\"event\":\"complete\"[^\n]*\n?$" "" data "${data}")
  elseif(case STREQUAL "generation")
    string(REPLACE "\"seed\":123" "\"seed\":\"123\"" data "${data}")
  elseif(case STREQUAL "path")
    string(REPLACE "profile-0-row-0.f32le" "../profile-0-row-0.f32le" data "${data}")
  endif()
  file(WRITE "${destination}/capture.jsonl" "${data}")
  if(case STREQUAL "row-fifo" OR case STREQUAL "metadata-fifo")
    if(case STREQUAL "row-fifo")
      set(pipe "${destination}/profile-0-row-0.f32le")
    else()
      set(pipe "${destination}/capture.jsonl")
    endif()
    file(REMOVE "${pipe}")
    execute_process(COMMAND "${FILE_FIXTURE}" --fifo "${pipe}" RESULT_VARIABLE rc TIMEOUT 10)
    if(NOT rc STREQUAL "0")
      message(FATAL_ERROR "Owned FIFO fixture creation failed: ${rc}")
    endif()
  endif()
  execute_process(COMMAND "${CANDIDATE}" --capture "${destination}" ${extra}
    OUTPUT_FILE "${OUTPUT}/${case}.txt" ERROR_FILE "${OUTPUT}/${case}.stderr" RESULT_VARIABLE rc TIMEOUT 30)
  file(WRITE "${OUTPUT}/${case}.exit" "${rc}\n")
  if(NOT rc STREQUAL "1")
    message(FATAL_ERROR "${case} refusal returned ${rc}, expected actual exit 1")
  endif()
endforeach()
message(STATUS "Complete offline mass/draw/residual fixtures agree; nine refusals pass; NOT-INFERENCE")
