# SPDX-License-Identifier: MIT
# Required-call vocabulary/mask/probability/lifetime fixtures; NOT-INFERENCE.
cmake_minimum_required(VERSION 3.21)
if(EXISTS "${OUTPUT}")
  message(FATAL_ERROR "Tool replay output must be new")
endif()
file(MAKE_DIRECTORY "${OUTPUT}")
execute_process(COMMAND "${CAPTURE}" --model :tools: --output-dir "${OUTPUT}/good" --tokens 8 --tools
  OUTPUT_FILE "${OUTPUT}/capture.stdout" ERROR_FILE "${OUTPUT}/capture.stderr" RESULT_VARIABLE rc TIMEOUT 30)
file(WRITE "${OUTPUT}/capture.exit" "${rc}\n")
if(NOT rc STREQUAL "0")
  message(FATAL_ERROR "Required-tool capture fixture failed: ${rc}")
endif()
foreach(arm IN ITEMS REFERENCE CANDIDATE FALLBACK)
  execute_process(COMMAND "${${arm}}" --capture "${OUTPUT}/good" --allow-synthetic
    OUTPUT_FILE "${OUTPUT}/${arm}.txt" ERROR_FILE "${OUTPUT}/${arm}.stderr" RESULT_VARIABLE rc TIMEOUT 30)
  file(WRITE "${OUTPUT}/${arm}.exit" "${rc}\n")
  if(NOT rc STREQUAL "0")
    message(FATAL_ERROR "${arm} required-tool replay exit ${rc}; logs preserved")
  endif()
  file(SHA256 "${OUTPUT}/${arm}.txt" ${arm}_hash)
endforeach()
if(NOT REFERENCE_hash STREQUAL CANDIDATE_hash OR NOT REFERENCE_hash STREQUAL FALLBACK_hash)
  message(FATAL_ERROR "Complete tool masks/probabilities/draws/completion witnesses differ")
endif()
file(READ "${OUTPUT}/good/capture.jsonl" original)
file(SHA256 "${OUTPUT}/good/vocabulary.bin" vocab_hash)
string(REGEX MATCH "\n\\{\"event\":\"row\"[^\n]*\n" first_row "${original}")
string(REGEX MATCH "\n\\{\"event\":\"profile_complete\"[^\n]*\n" first_complete "${original}")
if(NOT first_row OR NOT first_complete)
  message(FATAL_ERROR "Tool capture fixture row/completion missing")
endif()
foreach(case IN ITEMS policy premature-stop arguments vocabulary-hash vocabulary-truncated vocabulary-fifo
    vocabulary-symlink vocabulary-stop vocabulary-piece terminal)
  set(destination "${OUTPUT}/${case}")
  file(MAKE_DIRECTORY "${destination}")
  file(GLOB payloads "${OUTPUT}/good/*.f32le")
  file(COPY ${payloads} "${OUTPUT}/good/vocabulary.bin" DESTINATION "${destination}")
  set(data "${original}")
  if(case STREQUAL "policy")
    string(REPLACE "\"required\":true" "\"required\":false" data "${data}")
  elseif(case STREQUAL "premature-stop")
    string(STRIP "${first_row}" row)
    string(JSON row SET "${row}" stop true)
    string(JSON row SET "${row}" emitted 0)
    string(JSON row SET "${row}" token null)
    string(JSON row SET "${row}" position 5)
    string(REPLACE "\n" "" row "${row}")
    string(REPLACE "${first_row}" "\n${row}\n" data "${data}")
  elseif(case STREQUAL "arguments")
    string(STRIP "${first_complete}" completed)
    string(JSON size GET "${completed}" tool_call arguments size)
    math(EXPR different "(${size}+1)%10")
    string(JSON completed SET "${completed}" tool_call arguments size ${different})
    string(REPLACE "\n" "" completed "${completed}")
    string(REPLACE "${first_complete}" "\n${completed}\n" data "${data}")
  elseif(case STREQUAL "vocabulary-hash")
    string(REPEAT "0" 64 bad_hash)
    string(REPLACE "${vocab_hash}" "${bad_hash}" data "${data}")
  elseif(case STREQUAL "vocabulary-truncated")
    file(WRITE "${destination}/vocabulary.bin" "short")
  elseif(case STREQUAL "vocabulary-fifo" OR case STREQUAL "vocabulary-symlink")
    file(REMOVE "${destination}/vocabulary.bin")
    if(case STREQUAL "vocabulary-fifo")
      execute_process(COMMAND "${FILE_FIXTURE}" --fifo "${destination}/vocabulary.bin" RESULT_VARIABLE rc TIMEOUT 10)
      if(NOT rc STREQUAL "0")
        message(FATAL_ERROR "Owned vocabulary FIFO creation failed: ${rc}")
      endif()
    else()
      file(CREATE_LINK "../good/vocabulary.bin" "${destination}/vocabulary.bin" SYMBOLIC)
    endif()
  elseif(case STREQUAL "vocabulary-stop" OR case STREQUAL "vocabulary-piece")
    if(case STREQUAL "vocabulary-stop")
      set(mutation --invalid-stop)
    else()
      set(mutation --oversized-piece)
    endif()
    execute_process(COMMAND "${FILE_FIXTURE}" "${mutation}" "${destination}/vocabulary.bin" RESULT_VARIABLE rc TIMEOUT 10)
    if(NOT rc STREQUAL "0")
      message(FATAL_ERROR "Owned vocabulary corruption failed: ${rc}")
    endif()
    file(SHA256 "${destination}/vocabulary.bin" changed_hash)
    string(REPLACE "${vocab_hash}" "${changed_hash}" data "${data}")
  elseif(case STREQUAL "terminal")
    string(REGEX REPLACE "\\{\"event\":\"complete\"[^\n]*\n?$" "" data "${data}")
  endif()
  file(WRITE "${destination}/capture.jsonl" "${data}")
  execute_process(COMMAND "${CANDIDATE}" --capture "${destination}" --allow-synthetic
    OUTPUT_FILE "${OUTPUT}/${case}.txt" ERROR_FILE "${OUTPUT}/${case}.stderr" RESULT_VARIABLE rc TIMEOUT 30)
  file(WRITE "${OUTPUT}/${case}.exit" "${rc}\n")
  if(NOT rc STREQUAL "1")
    message(FATAL_ERROR "${case} refusal returned ${rc}, expected actual exit 1")
  endif()
endforeach()
message(STATUS "Complete required-tool masks/mass/draws agree; ten refusals pass; NOT-INFERENCE")
