# SPDX-License-Identifier: MIT
cmake_minimum_required(VERSION 3.21)
# HOST-NO-GPU: run the real Makefile/driver against isolated fake providers.
# A no-language Ninja project checks all product targets without compiling HIP.
find_program(MAKE_EXECUTABLE NAMES gmake make REQUIRED)
string(RANDOM LENGTH 12 ALPHABET 0123456789abcdef suffix)
set(root "${CMAKE_CURRENT_BINARY_DIR}/build-entry-fixture-${suffix}")
file(MAKE_DIRECTORY "${root}/cmake/provider")
file(COPY "${REPOSITORY}/Makefile" DESTINATION "${root}")
file(COPY "${REPOSITORY}/cmake/BuildTarget.cmake" DESTINATION "${root}/cmake")
file(COPY "${REPOSITORY}/cmake/provider/Source.cmake" DESTINATION "${root}/cmake/provider")
file(WRITE "${root}/cmake/provider/Fetch.cmake" [=[
include("${CMAKE_CURRENT_LIST_DIR}/Source.cmake")
file(MAKE_DIRECTORY "${LIE_SOURCE_ROOT}/.deps/gufo-f783fedb")
file(APPEND "${LIE_SOURCE_ROOT}/trace.txt" "fetch\n")
]=])
file(WRITE "${root}/cmake/provider/Build.cmake" [=[
include("${CMAKE_CURRENT_LIST_DIR}/Source.cmake")
foreach(name HIP_VISIBLE_DEVICES ROCR_VISIBLE_DEVICES CUDA_VISIBLE_DEVICES)
  if(NOT "$ENV{${name}}" STREQUAL "-1")
    message(FATAL_ERROR "GPU visibility was not disabled")
  endif()
endforeach()
file(MAKE_DIRECTORY "${LIE_SOURCE_ROOT}/.deps/gufo-state-access-${LABEL}" "${LIE_SOURCE_ROOT}/build/${LABEL}")
file(WRITE "${LIE_SOURCE_ROOT}/build/${LABEL}/fixture-architecture" "${LIE_HIP_ARCHITECTURE}")
file(APPEND "${LIE_SOURCE_ROOT}/trace.txt" "provider-${LIE_HIP_ARCHITECTURE}\n")
]=])
file(WRITE "${root}/cmake/provider/Verify.cmake" [=[
if(EXISTS "${GUFO_BUILD}/fixture-drift" OR NOT EXISTS "${GUFO_BUILD}/fixture-architecture")
  message(FATAL_ERROR "Synthetic provider drift")
endif()
]=])
file(WRITE "${root}/cmake/provider/Target.cmake" [=[
file(READ "${GUFO_BUILD}/fixture-architecture" actual)
if(NOT actual STREQUAL LIE_HIP_ARCHITECTURE)
  message(FATAL_ERROR "Synthetic provider target mismatch")
endif()
]=])
file(WRITE "${root}/CMakeLists.txt" [=[
cmake_minimum_required(VERSION 3.21)
project(build_entry_fixture LANGUAGES NONE)
if(NOT LIE_GUFO_RUNTIME OR NOT LIE_GUFO_STATE_ACCESS OR LIE_GUFO_REFERENCE_BENCH OR
   LIE_LEGACY_PYTHON_TESTS OR NOT CMAKE_DISABLE_FIND_PACKAGE_Python3 OR BUILD_TESTING OR
   LIE_CORE_ONLY OR LIE_Q2_QUALIFICATION_ONLY OR NOT LIE_DS4_RUNTIME_CACHE OR
   NOT LIE_C17_SAMPLING OR NOT LIE_VISION OR NOT LIE_MTP OR
   NOT LIE_DIRECTIONAL_STEERING OR NOT LIE_ATTENTION_DISPATCH_STATS OR
   NOT LIE_LONG_CONTEXT_WMMA OR NOT LIE_VISION_WEIGHT_DECODE OR NOT LIE_QWEN_Q2_FORMATS)
  message(FATAL_ERROR "Product selection mismatch")
endif()
if(EXISTS "${CMAKE_SOURCE_DIR}/configure-failure")
  message(FATAL_ERROR "Deliberate configure failure")
endif()
file(APPEND "${CMAKE_SOURCE_DIR}/trace.txt" "configure-${LIE_HIP_ARCHITECTURE}\n")
foreach(name synapse-lie-server synapse-lie-bench synapse-lie-bench-report synapse-lie-monitor synapse-lie-kvc lie-steering-build)
  add_custom_target(${name} COMMAND "${CMAKE_COMMAND}" -E touch "${CMAKE_BINARY_DIR}/${name}.fixture")
endforeach()
]=])

function(run_make target expected)
  execute_process(COMMAND "${CMAKE_COMMAND}" -E env --unset=SSH_CONNECTION
    "${MAKE_EXECUTABLE}" --no-print-directory "${target}" "CMAKE=${CMAKE_COMMAND}" ${ARGN}
    WORKING_DIRECTORY "${root}" RESULT_VARIABLE code
    OUTPUT_VARIABLE stdout ERROR_VARIABLE stderr TIMEOUT 30)
  file(APPEND "${root}/actual-commands.log" "target=${target}; exit=${code}\n${stdout}${stderr}\n")
  if(expected STREQUAL "PASS" AND NOT code STREQUAL "0")
    message(FATAL_ERROR "${target} failed: ${code}\n${stdout}${stderr}")
  elseif(expected STREQUAL "FAIL" AND code STREQUAL "0")
    message(FATAL_ERROR "${target} unexpectedly passed")
  endif()
endfunction()
run_make(help PASS)
run_make(strix-halo PASS JOBS=3)
file(READ "${root}/build/strix-halo/provider.json" pointer)
string(JSON first_label GET "${pointer}" label)
run_make(strix-halo PASS)
file(READ "${root}/build/strix-halo/provider.json" pointer)
string(JSON reused_label GET "${pointer}" label)
if(NOT first_label STREQUAL reused_label)
  message(FATAL_ERROR "Unchanged provider was rebuilt")
endif()
foreach(name synapse-lie-server synapse-lie-bench synapse-lie-bench-report synapse-lie-monitor synapse-lie-kvc lie-steering-build)
  if(NOT EXISTS "${root}/build/strix-halo/${name}.fixture")
    message(FATAL_ERROR "Product was not built: ${name}")
  endif()
endforeach()
file(WRITE "${root}/build/${first_label}/fixture-drift" "Synthetic drift\n")
run_make(strix-halo PASS)
file(READ "${root}/build/strix-halo/provider.json" pointer)
string(JSON rebuilt_label GET "${pointer}" label)
if(first_label STREQUAL rebuilt_label OR NOT EXISTS "${root}/build/${first_label}/fixture-drift")
  message(FATAL_ERROR "Drifting provider was reused or overwritten")
endif()
file(WRITE "${root}/build/${rebuilt_label}/fixture-architecture" "gfx1150")
run_make(strix-halo FAIL)
file(READ "${root}/build/strix-halo/provider.json" pointer)
string(JSON wrong_target_label GET "${pointer}" label)
if(NOT rebuilt_label STREQUAL wrong_target_label)
  message(FATAL_ERROR "Cross-target failure replaced the existing provider")
endif()
file(WRITE "${root}/build/${rebuilt_label}/fixture-architecture" "gfx1151")
run_make(strix-point PASS)
file(READ "${root}/trace.txt" trace)
string(REGEX MATCHALL "fetch\n" fetches "${trace}")
list(LENGTH fetches count)
if(NOT count EQUAL 1 OR NOT trace MATCHES "provider-gfx1150")
  message(FATAL_ERROR "Fetch or architecture selection mismatch")
endif()
run_make(strix-halo FAIL JOBS=0)
run_make(strix-halo FAIL JOBS=65)
file(WRITE "${root}/configure-failure" "Synthetic failure\n")
run_make(strix-halo FAIL)
file(GLOB results "${root}/evidence/strix-halo-build/*/result.json")
set(found_failure FALSE)
set(found_reuse FALSE)
foreach(path IN LISTS results)
  file(READ "${path}" record)
  string(JSON state GET "${record}" state)
  string(JSON count LENGTH "${record}" commands)
  if(state STREQUAL "FAILED")
    math(EXPR last "${count}-1")
    string(JSON phase GET "${record}" commands ${last} phase)
    string(JSON code GET "${record}" commands ${last} exit_code)
    if(phase STREQUAL "configure" AND NOT code EQUAL 0)
      set(found_failure TRUE)
    endif()
  else()
    string(JSON phase GET "${record}" commands 0 phase)
    if(phase STREQUAL "reuse-provider")
      set(found_reuse TRUE)
    endif()
  endif()
endforeach()
if(NOT found_failure OR NOT found_reuse)
  message(FATAL_ERROR "Original failure or reuse evidence was not retained")
endif()
message(STATUS "Native build entry contract passed; HOST-NO-GPU-BUILD, fixture only")
