# SPDX-License-Identifier: MIT
cmake_minimum_required(VERSION 3.21)
# Small synthetic manifests/archives exercise refusals; never provider evidence.
string(RANDOM LENGTH 12 ALPHABET 0123456789abcdef suffix)
set(root "${CMAKE_CURRENT_BINARY_DIR}/provider-fixture-${suffix}")
file(MAKE_DIRECTORY "${root}/cmake/provider" "${root}/cmake/gufo-runtime" "${root}/third_party" "${root}/.deps/pinned" "${root}/build/fake/src/models/qwen38_flash_next")
foreach(name Source Verify)
  file(COPY "${REPOSITORY}/cmake/provider/${name}.cmake" DESTINATION "${root}/cmake/provider")
endforeach()
file(WRITE "${root}/.deps/pinned/source.c" "Synthetic oracle, not Gufo source.\n")
file(SHA256 "${root}/.deps/pinned/source.c" source_hash)
set(pin f783fedb9bea2ec7de941f6da4e02f4a4596b29e)
file(WRITE "${root}/third_party/gufo-source.json" "{\"commit\":\"${pin}\",\"files\":{\"source.c\":\"${source_hash}\"}}")
file(WRITE "${root}/cmake/gufo-runtime/CMakeLists.txt" "# Synthetic recipe\n")
file(WRITE "${root}/build/fake/CMakeCache.txt" "# Synthetic cache\n")
set(libraries "{}")
foreach(name libgufo_core.a src/models/qwen38_flash_next/libgufo_qwen38_flash_next.a src/models/qwen38_flash_next/libgufo_qwen38_flash_next_mmq.a)
  file(WRITE "${root}/build/fake/${name}" "Synthetic archive placeholder, NOT-INFERENCE: ${name}\n")
  file(SHA256 "${root}/build/fake/${name}" hash)
  string(JSON libraries SET "${libraries}" "${name}" "\"${hash}\"")
endforeach()
file(SHA256 "${root}/third_party/gufo-source.json" manifest_hash)
file(SHA256 "${root}/cmake/gufo-runtime/CMakeLists.txt" recipe_hash)
file(SHA256 "${root}/build/fake/CMakeCache.txt" cache_hash)
file(MAKE_DIRECTORY "${root}/src" "${root}/include/lie" "${root}/adapters")
set(owned "{}")
foreach(name IN ITEMS src/sampling.c include/lie/sampling.h adapters/gufo_sampling.hpp)
  file(WRITE "${root}/${name}" "Synthetic owned sampling placeholder, NOT-INFERENCE.\n")
  file(SHA256 "${root}/${name}" hash)
  string(JSON owned SET "${owned}" "${name}" "\"${hash}\"")
endforeach()
set(receipt "{\"state\":\"LIBRARIES_BUILT_NOT_EXECUTED_NOT_INFERENCE_QUALIFIED\",\"source_pin\":\"${pin}\",\"source_manifest_sha256\":\"${manifest_hash}\",\"scope\":\"lie-qwen-only-source-subset\",\"subset_cmake_sha256\":\"${recipe_hash}\",\"cmake_cache_sha256\":\"${cache_hash}\",\"libraries\":${libraries}}")
string(JSON receipt SET "${receipt}" c17_sampling true)
string(JSON receipt SET "${receipt}" owned_sampling_files "${owned}")
set(owned_weights "{}")
foreach(name IN ITEMS src/weight_decode.c include/lie/weight_decode.h)
  file(WRITE "${root}/${name}" "Synthetic owned decoder placeholder, NOT-INFERENCE.\n")
  file(SHA256 "${root}/${name}" hash)
  string(JSON owned_weights SET "${owned_weights}" "${name}" "\"${hash}\"")
endforeach()
string(JSON receipt SET "${receipt}" vision_weight_decode true)
string(JSON receipt SET "${receipt}" owned_weight_decode_files "${owned_weights}")
file(WRITE "${root}/build/fake/BUILD-RECEIPT.json" "${receipt}")
function(check name expected)
  execute_process(COMMAND "${CMAKE_COMMAND}" "-DGUFO_SOURCE=${root}/.deps/pinned" "-DGUFO_BUILD=${root}/build/fake" -DLIE_GUFO_STATE_ACCESS=OFF -DLIE_DS4_RUNTIME_CACHE=OFF -P "${root}/cmake/provider/Verify.cmake" RESULT_VARIABLE rc OUTPUT_VARIABLE out ERROR_VARIABLE err)
  file(WRITE "${root}/${name}.log" "exit=${rc}\n${out}\n${err}")
  if(expected STREQUAL "pass")
    if(NOT rc STREQUAL "0")
      message(FATAL_ERROR "Expected successful synthetic verification: ${root}/${name}.log")
    endif()
  elseif(rc STREQUAL "0" OR NOT "${err}" MATCHES "${expected}")
    message(FATAL_ERROR "Expected refusal ${expected}: ${root}/${name}.log")
  endif()
endfunction()
check(valid pass)
foreach(pair IN ITEMS "source|.deps/pinned/source.c|Source/archive drift" "archive|build/fake/libgufo_core.a|Source/archive drift" "cache|build/fake/CMakeCache.txt|Provider CMake cache drift" "recipe|cmake/gufo-runtime/CMakeLists.txt|Provider build recipe drift" "sampling-source|src/sampling.c|Source/archive drift" "sampling-header|include/lie/sampling.h|Source/archive drift" "sampling-glue|adapters/gufo_sampling.hpp|Source/archive drift" "weight-source|src/weight_decode.c|Source/archive drift" "weight-header|include/lie/weight_decode.h|Source/archive drift")
  string(REPLACE "|" ";" parts "${pair}")
  list(GET parts 0 name)
  list(GET parts 1 path)
  list(GET parts 2 refusal)
  file(READ "${root}/${path}" original)
  file(APPEND "${root}/${path}" "changed")
  check("${name}" "${refusal}")
  file(WRITE "${root}/${path}" "${original}")
endforeach()
string(JSON changed SET "${receipt}" c17_sampling false)
file(WRITE "${root}/build/fake/BUILD-RECEIPT.json" "${changed}")
check(sampling-selection "Owned sampling build selection mismatch")
string(JSON changed REMOVE "${receipt}" owned_sampling_files "src/sampling.c")
file(WRITE "${root}/build/fake/BUILD-RECEIPT.json" "${changed}")
check(sampling-inventory "Owned sampling file inventory mismatch")
string(JSON changed SET "${receipt}" vision_weight_decode false)
file(WRITE "${root}/build/fake/BUILD-RECEIPT.json" "${changed}")
check(weight-selection "Vision weight decode build selection mismatch")
string(JSON changed REMOVE "${receipt}" owned_weight_decode_files "src/weight_decode.c")
file(WRITE "${root}/build/fake/BUILD-RECEIPT.json" "${changed}")
check(weight-inventory "Owned weight decode inventory mismatch")
string(JSON changed SET "${receipt}" state "\"FAILED\"")
file(WRITE "${root}/build/fake/BUILD-RECEIPT.json" "${changed}")
check(failed "Provider build/source identity mismatch")
string(JSON changed SET "${receipt}" source_variant "\"lie-state-access-v1\"")
file(WRITE "${root}/build/fake/BUILD-RECEIPT.json" "${changed}")
check(variant "Modified provider requires state access selection")
file(WRITE "${root}/build/fake/BUILD-RECEIPT.json" "${receipt}")
file(RENAME "${root}/build/fake/libgufo_core.a" "${root}/build/fake/saved.a")
file(CREATE_LINK "${root}/build/fake/saved.a" "${root}/build/fake/libgufo_core.a" SYMBOLIC)
check(symlink "Missing, linked or escaping source file")
file(REMOVE "${root}/build/fake/libgufo_core.a")
file(RENAME "${root}/build/fake/saved.a" "${root}/build/fake/libgufo_core.a")
check(restored pass)
file(REMOVE_RECURSE "${root}")
message(STATUS "Native provider verification refusals: PASS (synthetic manifest/archive fixtures, NOT-INFERENCE)")
