# SPDX-License-Identifier: MIT
# Evaluate only the provider's source-list declarations, with no HIP discovery,
# build, device access or model forward. Catch paths hidden from host fixtures.
file(READ "${SOURCE}/cmake/gufo-runtime/CMakeLists.txt" recipe)
string(FIND "${recipe}" "set(CORE\n" begin)
string(FIND "${recipe}" "add_library(gufo_core STATIC" end)
if(begin LESS 0 OR end LESS begin)
  message(FATAL_ERROR "Provider source-list section missing")
endif()
math(EXPR length "${end}-${begin}")
string(SUBSTRING "${recipe}" ${begin} ${length} declarations)
file(MAKE_DIRECTORY "${OUTPUT}")
file(WRITE "${OUTPUT}/source-list.cmake" "${declarations}")
set(LIE_ROOT "${SOURCE}")
set(GUFO_SOURCE "${SOURCE}/.deps/gufo-f783fedb")
include("${OUTPUT}/source-list.cmake")
set(checked 0)
foreach(path IN LISTS CORE)
  # A default CPU checkout need not fetch the optional upstream provider.
  cmake_path(IS_PREFIX GUFO_SOURCE "${path}" NORMALIZE upstream)
  if(upstream AND NOT EXISTS "${GUFO_SOURCE}")
    continue()
  endif()
  if(NOT IS_ABSOLUTE "${path}" OR NOT EXISTS "${path}" OR IS_DIRECTORY "${path}")
    message(FATAL_ERROR "Provider source path missing: ${path}")
  endif()
  math(EXPR checked "${checked}+1")
endforeach()
message(STATUS "Validated ${checked} provider source paths; HOST-NO-GPU-BUILD")
