# SPDX-License-Identifier: MIT
cmake_minimum_required(VERSION 3.21)
# Small synthetic manifests/archives exercise refusals; never provider evidence.
string(RANDOM LENGTH 12 ALPHABET 0123456789abcdef suffix)
set(root "${CMAKE_CURRENT_BINARY_DIR}/provider-fixture-${suffix}")
file(MAKE_DIRECTORY "${root}/cmake/provider" "${root}/cmake/gufo-runtime" "${root}/third_party" "${root}/.deps/pinned" "${root}/build/fake/src/models/qwen38_flash_next")
foreach(name Source Verify)
  file(COPY "${REPOSITORY}/cmake/provider/${name}.cmake" DESTINATION "${root}/cmake/provider")
endforeach()
file(WRITE "${root}/.deps/pinned/source.c" "Synthetic oracle, not Gufo source.\n")
file(SHA256 "${root}/.deps/pinned/source.c" source_hash)
set(pin f783fedb9bea2ec7de941f6da4e02f4a4596b29e)
file(WRITE "${root}/third_party/gufo-source.json" "{\"commit\":\"${pin}\",\"files\":{\"source.c\":\"${source_hash}\"}}")
file(WRITE "${root}/cmake/gufo-runtime/CMakeLists.txt" "# Synthetic recipe\n")
file(WRITE "${root}/build/fake/CMakeCache.txt" "# Synthetic cache\n")
set(libraries "{}")
foreach(name libgufo_core.a src/models/qwen38_flash_next/libgufo_qwen38_flash_next.a src/models/qwen38_flash_next/libgufo_qwen38_flash_next_mmq.a)
  file(WRITE "${root}/build/fake/${name}" "Synthetic archive placeholder, NOT-INFERENCE: ${name}\n")
  file(SHA256 "${root}/build/fake/${name}" hash)
  string(JSON libraries SET "${libraries}" "${name}" "\"${hash}\"")
endforeach()
file(SHA256 "${root}/third_party/gufo-source.json" manifest_hash)
file(SHA256 "${root}/cmake/gufo-runtime/CMakeLists.txt" recipe_hash)
file(SHA256 "${root}/build/fake/CMakeCache.txt" cache_hash)
file(MAKE_DIRECTORY "${root}/src" "${root}/include/lie" "${root}/adapters")
set(owned "{}")
foreach(name IN ITEMS src/sampling.c include/lie/sampling.h adapters/gufo_sampling.hpp src/sampling_history.c include/lie/sampling_history.h adapters/gufo_history.hpp src/sampling_distribution.c include/lie/sampling_distribution.h adapters/gufo_distribution.hpp src/grammar.c include/lie/grammar.h adapters/gufo_grammar.hpp src/grammar_number.c include/lie/grammar_number.h adapters/gufo_grammar_number.hpp src/grammar_regex.c include/lie/grammar_regex.h adapters/gufo_grammar_regex.hpp src/grammar_string.c include/lie/grammar_string.h adapters/gufo_grammar_string.hpp src/grammar_vocabulary.c include/lie/grammar_vocabulary.h adapters/gufo_grammar_vocabulary.hpp src/grammar_regex_compile.c include/lie/grammar_regex_compile.h adapters/gufo_grammar_regex_compile.hpp src/grammar_regex_parse.c include/lie/grammar_regex_parse.h adapters/gufo_grammar_regex_parse.hpp src/grammar_unicode.c include/lie/grammar_unicode.h src/grammar_builder.c include/lie/grammar_builder.h adapters/gufo_grammar_builder.hpp src/schema_transform.c include/lie/schema_transform.h adapters/gufo_schema_transform.hpp src/schema_internal.h src/schema_values.c include/lie/schema_values.h adapters/gufo_schema_values.hpp src/grammar_cache.c include/lie/grammar_cache.h adapters/gufo_grammar_cache.hpp src/schema_memo.c include/lie/schema_memo.h adapters/gufo_schema_memo.hpp src/schema_dispatch.c include/lie/schema_dispatch.h adapters/gufo_schema_dispatch.hpp src/schema_visit.c include/lie/schema_visit.h adapters/gufo_schema_visit.hpp src/schema_body.c include/lie/schema_body.h adapters/gufo_schema_body.hpp src/schema_number.c include/lie/schema_number.h adapters/gufo_schema_number.hpp src/schema_format.c include/lie/schema_format.h adapters/gufo_schema_format.hpp)
  file(WRITE "${root}/${name}" "Synthetic owned sampling placeholder, NOT-INFERENCE.\n")
  file(SHA256 "${root}/${name}" hash)
  string(JSON owned SET "${owned}" "${name}" "\"${hash}\"")
endforeach()
set(receipt "{\"state\":\"LIBRARIES_BUILT_NOT_EXECUTED_NOT_INFERENCE_QUALIFIED\",\"source_pin\":\"${pin}\",\"source_manifest_sha256\":\"${manifest_hash}\",\"scope\":\"lie-qwen-only-source-subset\",\"subset_cmake_sha256\":\"${recipe_hash}\",\"cmake_cache_sha256\":\"${cache_hash}\",\"libraries\":${libraries}}")
string(JSON receipt SET "${receipt}" c17_sampling true)
string(JSON receipt SET "${receipt}" owned_sampling_files "${owned}")
set(owned_weights "{}")
foreach(name IN ITEMS src/weight_decode.c include/lie/weight_decode.h)
  file(WRITE "${root}/${name}" "Synthetic owned decoder placeholder, NOT-INFERENCE.\n")
  file(SHA256 "${root}/${name}" hash)
  string(JSON owned_weights SET "${owned_weights}" "${name}" "\"${hash}\"")
endforeach()
string(JSON receipt SET "${receipt}" vision_weight_decode true)
string(JSON receipt SET "${receipt}" owned_weight_decode_files "${owned_weights}")
set(owned_steering "{}")
file(MAKE_DIRECTORY "${root}/adapters/hip")
foreach(name IN ITEMS src/steering_activation.c include/lie/steering_activation.h adapters/hip/steering.hpp adapters/hip/steering.hip)
  file(WRITE "${root}/${name}" "Synthetic owned steering placeholder, NOT-INFERENCE.\n")
  file(SHA256 "${root}/${name}" hash)
  string(JSON owned_steering SET "${owned_steering}" "${name}" "\"${hash}\"")
endforeach()
string(JSON receipt SET "${receipt}" directional_steering false)
string(JSON receipt SET "${receipt}" owned_steering_files "${owned_steering}")
file(WRITE "${root}/build/fake/BUILD-RECEIPT.json" "${receipt}")
function(check name expected)
  set(selected_access OFF)
  if(ARGC GREATER 2)
    set(selected_access "${ARGV2}")
  endif()
  execute_process(COMMAND "${CMAKE_COMMAND}" "-DGUFO_SOURCE=${root}/.deps/pinned" "-DGUFO_BUILD=${root}/build/fake" "-DLIE_GUFO_STATE_ACCESS=${selected_access}" -DLIE_DS4_RUNTIME_CACHE=OFF -DLIE_DIRECTIONAL_STEERING=OFF -P "${root}/cmake/provider/Verify.cmake" RESULT_VARIABLE rc OUTPUT_VARIABLE out ERROR_VARIABLE err)
  file(WRITE "${root}/${name}.log" "exit=${rc}\n${out}\n${err}")
  if(expected STREQUAL "pass")
    if(NOT rc STREQUAL "0")
      message(FATAL_ERROR "Expected successful synthetic verification: ${root}/${name}.log")
    endif()
  elseif(rc STREQUAL "0" OR NOT "${err}" MATCHES "${expected}")
    message(FATAL_ERROR "Expected refusal ${expected}: ${root}/${name}.log")
  endif()
endfunction()
check(valid pass)
foreach(pair IN ITEMS "schema-format-source|src/schema_format.c|Source/archive drift" "schema-format-header|include/lie/schema_format.h|Source/archive drift" "schema-format-glue|adapters/gufo_schema_format.hpp|Source/archive drift" "schema-number-source|src/schema_number.c|Source/archive drift" "schema-number-header|include/lie/schema_number.h|Source/archive drift" "schema-number-glue|adapters/gufo_schema_number.hpp|Source/archive drift" "source|.deps/pinned/source.c|Source/archive drift" "archive|build/fake/libgufo_core.a|Source/archive drift" "cache|build/fake/CMakeCache.txt|Provider CMake cache drift" "recipe|cmake/gufo-runtime/CMakeLists.txt|Provider build recipe drift" "sampling-source|src/sampling.c|Source/archive drift" "sampling-header|include/lie/sampling.h|Source/archive drift" "sampling-glue|adapters/gufo_sampling.hpp|Source/archive drift" "history-source|src/sampling_history.c|Source/archive drift" "history-header|include/lie/sampling_history.h|Source/archive drift" "history-glue|adapters/gufo_history.hpp|Source/archive drift" "distribution-source|src/sampling_distribution.c|Source/archive drift" "distribution-header|include/lie/sampling_distribution.h|Source/archive drift" "distribution-glue|adapters/gufo_distribution.hpp|Source/archive drift" "grammar-source|src/grammar.c|Source/archive drift" "grammar-header|include/lie/grammar.h|Source/archive drift" "grammar-glue|adapters/gufo_grammar.hpp|Source/archive drift" "number-source|src/grammar_number.c|Source/archive drift" "number-header|include/lie/grammar_number.h|Source/archive drift" "number-glue|adapters/gufo_grammar_number.hpp|Source/archive drift" "regex-source|src/grammar_regex.c|Source/archive drift" "regex-header|include/lie/grammar_regex.h|Source/archive drift" "regex-glue|adapters/gufo_grammar_regex.hpp|Source/archive drift" "string-source|src/grammar_string.c|Source/archive drift" "string-header|include/lie/grammar_string.h|Source/archive drift" "string-glue|adapters/gufo_grammar_string.hpp|Source/archive drift" "vocabulary-source|src/grammar_vocabulary.c|Source/archive drift" "vocabulary-header|include/lie/grammar_vocabulary.h|Source/archive drift" "vocabulary-glue|adapters/gufo_grammar_vocabulary.hpp|Source/archive drift" "compiler-source|src/grammar_regex_compile.c|Source/archive drift" "compiler-header|include/lie/grammar_regex_compile.h|Source/archive drift" "compiler-glue|adapters/gufo_grammar_regex_compile.hpp|Source/archive drift" "parser-source|src/grammar_regex_parse.c|Source/archive drift" "parser-header|include/lie/grammar_regex_parse.h|Source/archive drift" "parser-glue|adapters/gufo_grammar_regex_parse.hpp|Source/archive drift" "uset-source|src/grammar_unicode.c|Source/archive drift" "builder-source|src/grammar_builder.c|Source/archive drift" "builder-header|include/lie/grammar_builder.h|Source/archive drift" "builder-glue|adapters/gufo_grammar_builder.hpp|Source/archive drift" "schema-source|src/schema_transform.c|Source/archive drift" "schema-header|include/lie/schema_transform.h|Source/archive drift" "schema-glue|adapters/gufo_schema_transform.hpp|Source/archive drift" "schema-internal|src/schema_internal.h|Source/archive drift" "values-source|src/schema_values.c|Source/archive drift" "values-header|include/lie/schema_values.h|Source/archive drift" "values-glue|adapters/gufo_schema_values.hpp|Source/archive drift" "grammar-cache-source|src/grammar_cache.c|Source/archive drift" "grammar-cache-header|include/lie/grammar_cache.h|Source/archive drift" "grammar-cache-glue|adapters/gufo_grammar_cache.hpp|Source/archive drift" "schema-memo-source|src/schema_memo.c|Source/archive drift" "schema-memo-header|include/lie/schema_memo.h|Source/archive drift" "schema-memo-glue|adapters/gufo_schema_memo.hpp|Source/archive drift" "schema-dispatch-source|src/schema_dispatch.c|Source/archive drift" "schema-dispatch-header|include/lie/schema_dispatch.h|Source/archive drift" "schema-dispatch-glue|adapters/gufo_schema_dispatch.hpp|Source/archive drift" "schema-visit-source|src/schema_visit.c|Source/archive drift" "schema-visit-header|include/lie/schema_visit.h|Source/archive drift" "schema-visit-glue|adapters/gufo_schema_visit.hpp|Source/archive drift" "schema-body-source|src/schema_body.c|Source/archive drift" "schema-body-header|include/lie/schema_body.h|Source/archive drift" "schema-body-glue|adapters/gufo_schema_body.hpp|Source/archive drift" "uset-header|include/lie/grammar_unicode.h|Source/archive drift" "weight-source|src/weight_decode.c|Source/archive drift" "weight-header|include/lie/weight_decode.h|Source/archive drift")
  string(REPLACE "|" ";" parts "${pair}")
  list(GET parts 0 name)
  list(GET parts 1 path)
  list(GET parts 2 refusal)
  file(READ "${root}/${path}" original)
  file(APPEND "${root}/${path}" "changed")
  check("${name}" "${refusal}")
  file(WRITE "${root}/${path}" "${original}")
endforeach()
foreach(pair IN ITEMS "steering-source|src/steering_activation.c" "steering-header|include/lie/steering_activation.h" "steering-binding|adapters/hip/steering.hpp" "steering-kernel|adapters/hip/steering.hip")
  string(REPLACE "|" ";" parts "${pair}")
  list(GET parts 0 name)
  list(GET parts 1 path)
  file(READ "${root}/${path}" original)
  file(APPEND "${root}/${path}" "changed")
  check("${name}" "Source/archive drift")
  file(WRITE "${root}/${path}" "${original}")
endforeach()
string(JSON changed REMOVE "${receipt}" directional_steering)
file(WRITE "${root}/build/fake/BUILD-RECEIPT.json" "${changed}")
check(steering-identity "Directional steering build identity missing")
string(JSON changed SET "${receipt}" directional_steering true)
file(WRITE "${root}/build/fake/BUILD-RECEIPT.json" "${changed}")
check(steering-selection "Directional steering build selection mismatch")
string(JSON changed REMOVE "${receipt}" owned_steering_files "adapters/hip/steering.hip")
file(WRITE "${root}/build/fake/BUILD-RECEIPT.json" "${changed}")
check(steering-inventory "Owned steering file inventory mismatch")
string(JSON changed SET "${receipt}" c17_sampling false)
file(WRITE "${root}/build/fake/BUILD-RECEIPT.json" "${changed}")
check(sampling-selection "Owned sampling build selection mismatch")
string(JSON changed REMOVE "${receipt}" owned_sampling_files "src/sampling.c")
file(WRITE "${root}/build/fake/BUILD-RECEIPT.json" "${changed}")
check(sampling-inventory "Owned sampling file inventory mismatch")
string(JSON changed SET "${receipt}" vision_weight_decode false)
file(WRITE "${root}/build/fake/BUILD-RECEIPT.json" "${changed}")
check(weight-selection "Vision weight decode build selection mismatch")
string(JSON changed REMOVE "${receipt}" owned_weight_decode_files "src/weight_decode.c")
file(WRITE "${root}/build/fake/BUILD-RECEIPT.json" "${changed}")
check(weight-inventory "Owned weight decode inventory mismatch")
string(JSON changed SET "${receipt}" state "\"FAILED\"")
file(WRITE "${root}/build/fake/BUILD-RECEIPT.json" "${changed}")
check(failed "Provider build/source identity mismatch")
string(JSON changed SET "${receipt}" source_variant "\"lie-state-access-v1\"")
file(WRITE "${root}/build/fake/BUILD-RECEIPT.json" "${changed}")
check(variant "Modified provider requires state access selection")
file(WRITE "${root}/build/fake/BUILD-RECEIPT.json" "${receipt}")
file(RENAME "${root}/build/fake/libgufo_core.a" "${root}/build/fake/saved.a")
file(CREATE_LINK "${root}/build/fake/saved.a" "${root}/build/fake/libgufo_core.a" SYMBOLIC)
check(symlink "Missing, linked or escaping source file")
file(REMOVE "${root}/build/fake/libgufo_core.a")
file(RENAME "${root}/build/fake/saved.a" "${root}/build/fake/libgufo_core.a")
check(restored pass)
# Source construction is a synthetic stub for this receipt/refusal test only.
# Actual exact source replacements are exercised separately by pristine/ON/OFF.
# Execute the real verifier's selected-recipe gates without HIP discovery.
file(APPEND "${root}/cmake/provider/Source.cmake" [=[
function(lie_variant_files state_access kvc out_files out_changed)
  file(READ "${LIE_SOURCE_ROOT}/third_party/gufo-source.json" manifest)
  string(JSON files GET "${manifest}" files)
  set(${out_files} "${files}" PARENT_SCOPE)
  set(${out_changed} "{}" PARENT_SCOPE)
endfunction()
]=])
set(selected "${receipt}")
string(JSON selected SET "${selected}" source_variant "\"lie-state-access-v1\"")
file(READ "${root}/third_party/gufo-source.json" manifest)
string(JSON files GET "${manifest}" files)
string(JSON selected SET "${selected}" variant_files "${files}")
file(MAKE_DIRECTORY "${root}/adapters/gufo-state")
foreach(pair IN ITEMS "access|state_access" "sampling|sampling" "dense-sampling|dense_sampling" "history-sampling|history_sampling" "distribution-sampling|distribution_sampling" "grammar-runtime|grammar_runtime" "grammar-cache|grammar_cache" "schema-memo|schema_memo" "schema-dispatch|schema_dispatch" "schema-visit|schema_visit" "schema-body|schema_body" "schema-format|schema_format" "schema-values|schema_values" "schema-transform|schema_transform" "grammar-number|grammar_number" "grammar-regex|grammar_regex" "grammar-string|grammar_string" "grammar-vocabulary|grammar_vocabulary" "grammar-compiler|grammar_compiler" "grammar-parser|grammar_parser" "vision-weight|vision_weight" "steering|steering")
  string(REPLACE "|" ";" parts "${pair}")
  list(GET parts 0 name)
  list(GET parts 1 field)
  file(WRITE "${root}/adapters/gufo-state/${name}-edits.json" "Synthetic selected recipe: ${name}; NOT-INFERENCE.\n")
  file(SHA256 "${root}/adapters/gufo-state/${name}-edits.json" hash)
  string(JSON selected SET "${selected}" "${field}_edits_sha256" "\"${hash}\"")
endforeach()
file(WRITE "${root}/build/fake/BUILD-RECEIPT.json" "${selected}")
check(selected-recipe-valid pass ON)
string(JSON changed SET "${selected}" schema_visit_edits_sha256 "\"wrong-hash\"")
file(WRITE "${root}/build/fake/BUILD-RECEIPT.json" "${changed}")
check(schema-visit-recipe-hash "Owned schema visit edit provenance mismatch" ON)
string(JSON changed REMOVE "${selected}" schema_visit_edits_sha256)
file(WRITE "${root}/build/fake/BUILD-RECEIPT.json" "${changed}")
check(schema-visit-recipe-missing "schema_visit_edits_sha256" ON)
file(WRITE "${root}/build/fake/BUILD-RECEIPT.json" "${selected}")
file(READ "${root}/adapters/gufo-state/schema-visit-edits.json" visit_recipe)
file(APPEND "${root}/adapters/gufo-state/schema-visit-edits.json" "changed")
check(schema-visit-recipe-drift "Owned schema visit edit provenance mismatch" ON)
file(WRITE "${root}/adapters/gufo-state/schema-visit-edits.json" "${visit_recipe}")
string(JSON changed SET "${selected}" schema_body_edits_sha256 "\"wrong-hash\"")
file(WRITE "${root}/build/fake/BUILD-RECEIPT.json" "${changed}")
check(schema-body-recipe-hash "Owned schema body edit provenance mismatch" ON)
string(JSON changed REMOVE "${selected}" schema_body_edits_sha256)
file(WRITE "${root}/build/fake/BUILD-RECEIPT.json" "${changed}")
check(schema-body-recipe-missing "schema_body_edits_sha256" ON)
file(WRITE "${root}/build/fake/BUILD-RECEIPT.json" "${selected}")
file(READ "${root}/adapters/gufo-state/schema-body-edits.json" body_recipe)
file(APPEND "${root}/adapters/gufo-state/schema-body-edits.json" "changed")
check(schema-body-recipe-drift "Owned schema body edit provenance mismatch" ON)
file(WRITE "${root}/adapters/gufo-state/schema-body-edits.json" "${body_recipe}")
string(JSON changed SET "${selected}" schema_format_edits_sha256 "\"wrong-hash\"")
file(WRITE "${root}/build/fake/BUILD-RECEIPT.json" "${changed}")
check(schema-format-recipe-hash "Owned schema format edit provenance mismatch" ON)
string(JSON changed REMOVE "${selected}" schema_format_edits_sha256)
file(WRITE "${root}/build/fake/BUILD-RECEIPT.json" "${changed}")
check(schema-format-recipe-missing "schema_format_edits_sha256" ON)
file(WRITE "${root}/build/fake/BUILD-RECEIPT.json" "${selected}")
file(READ "${root}/adapters/gufo-state/schema-format-edits.json" format_recipe)
file(APPEND "${root}/adapters/gufo-state/schema-format-edits.json" "changed")
check(schema-format-recipe-drift "Owned schema format edit provenance mismatch" ON)
file(WRITE "${root}/adapters/gufo-state/schema-format-edits.json" "${format_recipe}")
string(JSON changed SET "${selected}" schema_dispatch_edits_sha256 "\"wrong-hash\"")
file(WRITE "${root}/build/fake/BUILD-RECEIPT.json" "${changed}")
check(schema-dispatch-recipe-hash "Owned schema dispatch edit provenance mismatch" ON)
string(JSON changed REMOVE "${selected}" schema_dispatch_edits_sha256)
file(WRITE "${root}/build/fake/BUILD-RECEIPT.json" "${changed}")
check(schema-dispatch-recipe-missing "schema_dispatch_edits_sha256" ON)
file(WRITE "${root}/build/fake/BUILD-RECEIPT.json" "${selected}")
file(READ "${root}/adapters/gufo-state/schema-dispatch-edits.json" dispatch_recipe)
file(APPEND "${root}/adapters/gufo-state/schema-dispatch-edits.json" "changed")
check(schema-dispatch-recipe-drift "Owned schema dispatch edit provenance mismatch" ON)
file(WRITE "${root}/adapters/gufo-state/schema-dispatch-edits.json" "${dispatch_recipe}")
string(JSON changed SET "${selected}" schema_memo_edits_sha256 "\"wrong-hash\"")
file(WRITE "${root}/build/fake/BUILD-RECEIPT.json" "${changed}")
check(schema-memo-recipe-hash "Owned schema memo edit provenance mismatch" ON)
string(JSON changed REMOVE "${selected}" schema_memo_edits_sha256)
file(WRITE "${root}/build/fake/BUILD-RECEIPT.json" "${changed}")
check(schema-memo-recipe-missing "schema_memo_edits_sha256" ON)
file(WRITE "${root}/build/fake/BUILD-RECEIPT.json" "${selected}")
file(READ "${root}/adapters/gufo-state/schema-memo-edits.json" memo_recipe)
file(APPEND "${root}/adapters/gufo-state/schema-memo-edits.json" "changed")
check(schema-memo-recipe-drift "Owned schema memo edit provenance mismatch" ON)
file(WRITE "${root}/adapters/gufo-state/schema-memo-edits.json" "${memo_recipe}")
string(JSON changed SET "${selected}" grammar_cache_edits_sha256 "\"wrong-hash\"")
file(WRITE "${root}/build/fake/BUILD-RECEIPT.json" "${changed}")
check(grammar-cache-recipe-hash "Owned grammar cache edit provenance mismatch" ON)
string(JSON changed REMOVE "${selected}" grammar_cache_edits_sha256)
file(WRITE "${root}/build/fake/BUILD-RECEIPT.json" "${changed}")
check(grammar-cache-recipe-missing "grammar_cache_edits_sha256" ON)
file(WRITE "${root}/build/fake/BUILD-RECEIPT.json" "${selected}")
file(APPEND "${root}/adapters/gufo-state/grammar-cache-edits.json" "changed")
check(grammar-cache-recipe-drift "Owned grammar cache edit provenance mismatch" ON)
file(REMOVE_RECURSE "${root}")
message(STATUS "Native provider verification refusals: PASS (synthetic manifest/archive fixtures, NOT-INFERENCE)")
