# SPDX-License-Identifier: MIT
cmake_minimum_required(VERSION 3.21)
# Source composition and synthetic GGUF metadata only. No HIP, model or network.
get_filename_component(REPOSITORY "${REPOSITORY}" ABSOLUTE)
set(pristine "${REPOSITORY}/.deps/gufo-f783fedb")
find_program(PATCH_PROGRAM NAMES patch)
find_program(CXX_PROGRAM NAMES c++ g++ clang++)
if(NOT EXISTS "${pristine}" OR NOT PATCH_PROGRAM OR NOT CXX_PROGRAM)
  message(STATUS "SKIP optional pinned source/patch/C++ host check; NOT-INFERENCE")
  return()
endif()
include("${REPOSITORY}/cmake/provider/Source.cmake")
file(READ "${REPOSITORY}/adapters/gufo-state/qwen-q2-format-edits.json" recipe)
string(JSON selected_files GET "${recipe}" selected_files_sha256)
string(JSON file_count LENGTH "${selected_files}")
string(JSON edit_count LENGTH "${recipe}" edits)
if(NOT file_count EQUAL 15 OR NOT edit_count EQUAL 38)
  message(FATAL_ERROR "Unexpected selected Q2 source boundary")
endif()
string(RANDOM LENGTH 12 ALPHABET 0123456789abcdef suffix)
set(root "${REPOSITORY}/build/qwen-format-${suffix}")
file(MAKE_DIRECTORY "${root}/standalone" "${root}/combined")
set(LIE_QWEN_Q2_FORMATS OFF)
lie_variant_files(ON ON old_files old_changed)
set(LIE_QWEN_Q2_FORMATS ON)
lie_variant_files(ON ON new_files new_changed)
math(EXPR last "${file_count}-1")
foreach(i RANGE 0 ${last})
  string(JSON name MEMBER "${selected_files}" ${i})
  get_filename_component(parent "${name}" DIRECTORY)
  file(MAKE_DIRECTORY "${root}/standalone/${parent}" "${root}/combined/${parent}")
  configure_file("${pristine}/${name}" "${root}/standalone/${name}" COPYONLY)
  string(JSON content ERROR_VARIABLE absent GET "${old_changed}" "${name}")
  if(absent)
    configure_file("${pristine}/${name}" "${root}/combined/${name}" COPYONLY)
  else()
    file(WRITE "${root}/combined/${name}" "${content}")
  endif()
endforeach()
foreach(variant IN ITEMS standalone combined)
  execute_process(COMMAND "${PATCH_PROGRAM}" --batch --fuzz=0 --no-backup-if-mismatch
    -p1 -i "${REPOSITORY}/patches/gufo-q2.patch"
    WORKING_DIRECTORY "${root}/${variant}" RESULT_VARIABLE code
    OUTPUT_FILE "${root}/${variant}-patch.log" ERROR_FILE "${root}/${variant}-patch.log")
  if(NOT code STREQUAL "0")
    message(FATAL_ERROR "Selected ${variant} patch failed (${code}); retained ${root}")
  endif()
endforeach()
lie_verify_files("${root}/standalone" "${selected_files}")
foreach(i RANGE 0 ${last})
  string(JSON name MEMBER "${selected_files}" ${i})
  file(SHA256 "${root}/combined/${name}" actual)
  string(JSON expected GET "${new_files}" "${name}")
  if(NOT actual STREQUAL expected)
    message(FATAL_ERROR "Combined Q2 source differs from selected patch: ${name}")
  endif()
endforeach()
string(JSON count LENGTH "${old_files}")
math(EXPR last "${count}-1")
foreach(i RANGE 0 ${last})
  string(JSON name MEMBER "${old_files}" ${i})
  string(JSON selected ERROR_VARIABLE absent GET "${selected_files}" "${name}")
  if(absent)
    string(JSON before GET "${old_files}" "${name}")
    string(JSON after GET "${new_files}" "${name}")
    if(NOT before STREQUAL after)
      message(FATAL_ERROR "Q2 option changed unrelated provider source: ${name}")
    endif()
  endif()
endforeach()
# Headers modified by current non-format recipes participate in this host check.
string(JSON count LENGTH "${new_changed}")
math(EXPR last "${count}-1")
foreach(i RANGE 0 ${last})
  string(JSON name MEMBER "${new_changed}" ${i})
  string(JSON content GET "${new_changed}" "${name}")
  get_filename_component(parent "${root}/combined/${name}" DIRECTORY)
  file(MAKE_DIRECTORY "${parent}")
  file(WRITE "${root}/combined/${name}" "${content}")
endforeach()
set(flags -std=c++20 -O0 -g -UNDEBUG)
if(SANITIZERS)
  list(APPEND flags -fsanitize=address,undefined -fno-omit-frame-pointer)
endif()
execute_process(COMMAND "${CXX_PROGRAM}" ${flags}
  "-I${root}/combined" "-I${pristine}" "-I${REPOSITORY}/include"
  "-I${REPOSITORY}/adapters"
  "${root}/combined/tests/models/qwen38_flash_next/config_test.cpp"
  "${root}/combined/src/models/qwen38_flash_next/config.cpp"
  "${pristine}/src/core/gguf_reader.cpp"
  "${root}/combined/src/core/quant/ggml_dequant.cpp"
  -o "${root}/metadata-fixture"
  RESULT_VARIABLE code OUTPUT_FILE "${root}/compile.log" ERROR_FILE "${root}/compile.log"
  TIMEOUT 120)
if(NOT code STREQUAL "0")
  message(FATAL_ERROR "Q2 synthetic metadata compile failed (${code}); retained ${root}")
endif()
execute_process(COMMAND "${root}/metadata-fixture" RESULT_VARIABLE code
  OUTPUT_FILE "${root}/metadata.log" ERROR_FILE "${root}/metadata.log" TIMEOUT 30)
if(NOT code STREQUAL "0")
  message(FATAL_ERROR "Q2 synthetic metadata failed (${code}); retained ${root}")
endif()
file(REMOVE_RECURSE "${root}")
message(STATUS "Selected Q2 source: 15 files / 38 hunks match; synthetic metadata PASS; NOT-INFERENCE")
