# SPDX-License-Identifier: MIT
cmake_minimum_required(VERSION 3.21)
include("${CMAKE_CURRENT_LIST_DIR}/Source.cmake")
if(NOT DEFINED LABEL OR NOT LABEL MATCHES "^[a-z0-9-]+$")
  message(FATAL_ERROR "Usage: cmake -DLABEL=exclusive-label -P cmake/provider/Build.cmake")
endif()
string(LENGTH "${LABEL}" label_length)
if(label_length GREATER 48 OR DEFINED ENV{SSH_CONNECTION})
  message(FATAL_ERROR "Local-only build requires a short exclusive label; remote builds require the lease runner")
endif()
if(NOT DEFINED LIE_GUFO_STATE_ACCESS)
  set(LIE_GUFO_STATE_ACCESS ON)
endif()
if(NOT DEFINED LIE_DS4_RUNTIME_CACHE)
  set(LIE_DS4_RUNTIME_CACHE ON)
endif()
if(LIE_DS4_RUNTIME_CACHE AND NOT LIE_GUFO_STATE_ACCESS)
  message(FATAL_ERROR "DS4 state requires state access")
endif()
set(build "${LIE_SOURCE_ROOT}/build/${LABEL}")
set(out "${LIE_SOURCE_ROOT}/evidence/${LABEL}")
if(EXISTS "${build}" OR EXISTS "${out}")
  message(FATAL_ERROR "Build/evidence label exists; refusing replacement")
endif()
set(source "${LIE_SOURCE_ROOT}/.deps/gufo-f783fedb")
lie_variant_files("${LIE_GUFO_STATE_ACCESS}" "${LIE_DS4_RUNTIME_CACHE}" files changed)
file(READ "${LIE_SOURCE_ROOT}/third_party/gufo-source.json" manifest)
string(JSON pristine GET "${manifest}" files)
lie_verify_files("${source}" "${pristine}")
if(LIE_GUFO_STATE_ACCESS)
  set(source "${LIE_SOURCE_ROOT}/.deps/gufo-state-access-${LABEL}")
  if(EXISTS "${source}")
    message(FATAL_ERROR "Variant directory exists; refusing replacement")
  endif()
  string(JSON count LENGTH "${files}")
  math(EXPR last "${count}-1")
  foreach(i RANGE 0 ${last})
    string(JSON name MEMBER "${files}" ${i})
    get_filename_component(parent "${source}/${name}" DIRECTORY)
    file(MAKE_DIRECTORY "${parent}")
    string(JSON content ERROR_VARIABLE absent GET "${changed}" "${name}")
    if(absent)
      configure_file("${LIE_SOURCE_ROOT}/.deps/gufo-f783fedb/${name}" "${source}/${name}" COPYONLY)
    else()
      file(WRITE "${source}/${name}" "${content}")
    endif()
  endforeach()
endif()
lie_verify_files("${source}" "${files}")
file(MAKE_DIRECTORY "${build}/private-home" "${build}/tmp" "${out}")
set(receipt "{}")
foreach(field IN ITEMS source_pin source build scope)
  if(field STREQUAL "source_pin")
    set(value "${LIE_GUFO_PIN}")
  elseif(field STREQUAL "scope")
    set(value lie-qwen-only-source-subset)
  else()
    set(value "${${field}}")
  endif()
  lie_json_quote(quoted "${value}")
  string(JSON receipt SET "${receipt}" "${field}" "${quoted}")
endforeach()
string(JSON receipt SET "${receipt}" state "\"RUNNING\"")
string(JSON receipt SET "${receipt}" gpu_execution false)
string(JSON receipt SET "${receipt}" installation false)
string(JSON receipt SET "${receipt}" commands "[]")
file(WRITE "${out}/result.json" "${receipt}\n")
# A child-only environment prevents user flags or a preload from changing the
# recorded recipe. The controlling shell's environment is never modified.
set(child_env "${CMAKE_COMMAND}" -E env --unset=LD_PRELOAD --unset=LD_LIBRARY_PATH
  --unset=CC --unset=CXX --unset=CFLAGS --unset=CXXFLAGS --unset=HIPFLAGS
  --unset=HIPCC_COMPILE_FLAGS_APPEND --unset=HIPCC_LINK_FLAGS_APPEND
  "HOME=${build}/private-home" "XDG_CACHE_HOME=${build}/private-home/cache"
  "TMPDIR=${build}/tmp" LC_ALL=C HIP_VISIBLE_DEVICES=-1 ROCR_VISIBLE_DEVICES=-1 CUDA_VISIBLE_DEVICES=-1)
# Mirror the previous verifier's compiler/provider environment isolation.
execute_process(COMMAND "${CMAKE_COMMAND}" -E environment OUTPUT_VARIABLE current_environment)
string(REPLACE "\n" ";" environment_lines "${current_environment}")
foreach(line IN LISTS environment_lines)
  if(line MATCHES "^((GUFO_|DS4_)[A-Za-z0-9_]+)=")
    list(INSERT child_env 3 "--unset=${CMAKE_MATCH_1}")
  endif()
endforeach()
unset(current_environment)
unset(environment_lines)
function(run_recorded label)
  execute_process(COMMAND ${child_env} ${ARGN} WORKING_DIRECTORY "${LIE_SOURCE_ROOT}"
    OUTPUT_FILE "${out}/${label}.log" ERROR_FILE "${out}/${label}.log"
    TIMEOUT 5400 RESULT_VARIABLE result)
  set(command "[]")
  set(index 0)
  foreach(argument IN LISTS ARGN)
    lie_json_quote(quoted "${argument}")
    string(JSON command SET "${command}" ${index} "${quoted}")
    math(EXPR index "${index}+1")
  endforeach()
  set(row "{}")
  string(JSON row SET "${row}" argv "${command}")
  if(result MATCHES "^[0-9]+$")
    string(JSON row SET "${row}" exit_code "${result}")
  else()
    lie_json_quote(quoted "${result}")
    string(JSON row SET "${row}" failure "${quoted}")
  endif()
  string(JSON count LENGTH "${receipt}" commands)
  string(JSON receipt SET "${receipt}" commands ${count} "${row}")
  if(NOT result STREQUAL "0")
    string(JSON receipt SET "${receipt}" state "\"FAILED\"")
  endif()
  file(WRITE "${out}/result.json" "${receipt}\n")
  set(receipt "${receipt}" PARENT_SCOPE)
  if(NOT result STREQUAL "0")
    message(FATAL_ERROR "${label} failed (${result}); logs retained under ${out}")
  endif()
endfunction()
run_recorded(configure "${CMAKE_COMMAND}" -S "${LIE_SOURCE_ROOT}/cmake/gufo-runtime" -B "${build}" -G Ninja
  "-DGUFO_SOURCE=${source}" -DCMAKE_BUILD_TYPE=RelWithDebInfo -DBUILD_TESTING=OFF
  -DGUFO_BUILD_TOOLS=OFF -DENGINE_ENABLE_HIP=ON -DCMAKE_HIP_ARCHITECTURES=gfx1151
  "-DCMAKE_CXX_FLAGS=-include chrono" "-DCMAKE_HIP_FLAGS=-include chrono" "-DGUFO_REVISION=${LIE_GUFO_PIN}")
run_recorded(build "${CMAKE_COMMAND}" --build "${build}" --target gufo_qwen38_flash_next --parallel 1)
lie_verify_files("${source}" "${files}")
set(libraries "{}")
foreach(name IN ITEMS libgufo_core.a src/models/qwen38_flash_next/libgufo_qwen38_flash_next.a src/models/qwen38_flash_next/libgufo_qwen38_flash_next_mmq.a)
  file(SHA256 "${build}/${name}" hash)
  string(JSON libraries SET "${libraries}" "${name}" "\"${hash}\"")
endforeach()
string(JSON receipt SET "${receipt}" libraries "${libraries}")
foreach(pair IN ITEMS "source_manifest_sha256|third_party/gufo-source.json" "subset_cmake_sha256|cmake/gufo-runtime/CMakeLists.txt")
  string(REPLACE "|" ";" parts "${pair}")
  list(GET parts 0 field)
  list(GET parts 1 name)
  file(SHA256 "${LIE_SOURCE_ROOT}/${name}" hash)
  string(JSON receipt SET "${receipt}" "${field}" "\"${hash}\"")
endforeach()
file(SHA256 "${build}/CMakeCache.txt" hash)
string(JSON receipt SET "${receipt}" cmake_cache_sha256 "\"${hash}\"")
if(LIE_GUFO_STATE_ACCESS)
  file(SHA256 "${LIE_SOURCE_ROOT}/adapters/gufo-state/sampling-edits.json" hash)
  string(JSON receipt SET "${receipt}" sampling_edits_sha256 "\"${hash}\"")
  set(variant lie-state-access-v1)
  if(LIE_DS4_RUNTIME_CACHE)
    set(variant lie-ds4-state-v1)
    file(SHA256 "${LIE_SOURCE_ROOT}/adapters/gufo-state/kvc-edits.json" hash)
    string(JSON receipt SET "${receipt}" kvc_edits_sha256 "\"${hash}\"")
  endif()
  file(SHA256 "${LIE_SOURCE_ROOT}/adapters/gufo-state/access-edits.json" hash)
  string(JSON receipt SET "${receipt}" state_access_edits_sha256 "\"${hash}\"")
  string(JSON receipt SET "${receipt}" source_variant "\"${variant}\"")
  string(JSON receipt SET "${receipt}" variant_files "${files}")
endif()
string(JSON receipt SET "${receipt}" state "\"LIBRARIES_BUILT_NOT_EXECUTED_NOT_INFERENCE_QUALIFIED\"")
file(WRITE "${build}/BUILD-RECEIPT.json" "${receipt}\n")
file(WRITE "${out}/result.json" "${receipt}\n")
message(STATUS "Provider libraries built and verified; no inference execution")
