# SPDX-License-Identifier: MIT
cmake_minimum_required(VERSION 3.21)
include("${CMAKE_CURRENT_LIST_DIR}/Source.cmake")
if(NOT DEFINED LABEL OR NOT LABEL MATCHES "^[a-z0-9-]+$")
  message(FATAL_ERROR "Usage: cmake -DLABEL=exclusive-label -P cmake/provider/Build.cmake")
endif()
string(LENGTH "${LABEL}" label_length)
if(label_length GREATER 48 OR DEFINED ENV{SSH_CONNECTION})
  message(FATAL_ERROR "Local-only build requires a short exclusive label; remote builds require the lease runner")
endif()
if(NOT DEFINED LIE_GUFO_STATE_ACCESS)
  set(LIE_GUFO_STATE_ACCESS ON)
endif()
if(NOT DEFINED LIE_DS4_RUNTIME_CACHE)
  set(LIE_DS4_RUNTIME_CACHE ON)
endif()
if(NOT DEFINED LIE_C17_SAMPLING)
  set(LIE_C17_SAMPLING ON)
endif()
if(NOT DEFINED LIE_VISION_WEIGHT_DECODE)
  set(LIE_VISION_WEIGHT_DECODE ON)
endif()
if(NOT DEFINED LIE_DIRECTIONAL_STEERING)
  set(LIE_DIRECTIONAL_STEERING ON)
endif()
if(LIE_DIRECTIONAL_STEERING AND NOT LIE_GUFO_STATE_ACCESS)
  message(FATAL_ERROR "Directional steering requires the verified state-access variant")
endif()
if(NOT DEFINED LIE_HIP_ARCHITECTURE)
  set(LIE_HIP_ARCHITECTURE gfx1151)
endif()
if(NOT LIE_HIP_ARCHITECTURE MATCHES "^gfx115[01]$")
  message(FATAL_ERROR "LIE_HIP_ARCHITECTURE must be gfx1150 or gfx1151")
endif()
if(LIE_DS4_RUNTIME_CACHE AND NOT LIE_GUFO_STATE_ACCESS)
  message(FATAL_ERROR "DS4 state requires state access")
endif()
set(build "${LIE_SOURCE_ROOT}/build/${LABEL}")
set(out "${LIE_SOURCE_ROOT}/evidence/${LABEL}")
if(EXISTS "${build}" OR EXISTS "${out}")
  message(FATAL_ERROR "Build/evidence label exists; refusing replacement")
endif()
set(source "${LIE_SOURCE_ROOT}/.deps/gufo-f783fedb")
lie_variant_files("${LIE_GUFO_STATE_ACCESS}" "${LIE_DS4_RUNTIME_CACHE}" files changed)
file(READ "${LIE_SOURCE_ROOT}/third_party/gufo-source.json" manifest)
string(JSON pristine GET "${manifest}" files)
lie_verify_files("${source}" "${pristine}")
if(LIE_GUFO_STATE_ACCESS)
  set(source "${LIE_SOURCE_ROOT}/.deps/gufo-state-access-${LABEL}")
  if(EXISTS "${source}")
    message(FATAL_ERROR "Variant directory exists; refusing replacement")
  endif()
  string(JSON count LENGTH "${files}")
  math(EXPR last "${count}-1")
  foreach(i RANGE 0 ${last})
    string(JSON name MEMBER "${files}" ${i})
    get_filename_component(parent "${source}/${name}" DIRECTORY)
    file(MAKE_DIRECTORY "${parent}")
    string(JSON content ERROR_VARIABLE absent GET "${changed}" "${name}")
    if(absent)
      configure_file("${LIE_SOURCE_ROOT}/.deps/gufo-f783fedb/${name}" "${source}/${name}" COPYONLY)
    else()
      file(WRITE "${source}/${name}" "${content}")
    endif()
  endforeach()
endif()
lie_verify_files("${source}" "${files}")
file(MAKE_DIRECTORY "${build}/private-home" "${build}/tmp" "${out}")
set(receipt "{}")
foreach(field IN ITEMS source_pin source build scope)
  if(field STREQUAL "source_pin")
    set(value "${LIE_GUFO_PIN}")
  elseif(field STREQUAL "scope")
    set(value lie-qwen-only-source-subset)
  else()
    set(value "${${field}}")
  endif()
  lie_json_quote(quoted "${value}")
  string(JSON receipt SET "${receipt}" "${field}" "${quoted}")
endforeach()
string(JSON receipt SET "${receipt}" state "\"RUNNING\"")
string(JSON receipt SET "${receipt}" gpu_execution false)
string(JSON receipt SET "${receipt}" installation false)
string(JSON receipt SET "${receipt}" commands "[]")
string(JSON receipt SET "${receipt}" hip_architecture "\"${LIE_HIP_ARCHITECTURE}\"")
file(SHA256 "${LIE_SOURCE_ROOT}/cmake/hip-target.cmake" hip_policy_hash)
string(JSON receipt SET "${receipt}" hip_target_cmake_sha256 "\"${hip_policy_hash}\"")
file(WRITE "${out}/result.json" "${receipt}\n")
# A child-only environment prevents user flags or a preload from changing the
# recorded recipe. The controlling shell's environment is never modified.
set(child_env "${CMAKE_COMMAND}" -E env --unset=LD_PRELOAD --unset=LD_LIBRARY_PATH
  --unset=CC --unset=CXX --unset=CFLAGS --unset=CXXFLAGS --unset=HIPFLAGS
  --unset=HIPCC_COMPILE_FLAGS_APPEND --unset=HIPCC_LINK_FLAGS_APPEND
  "XDG_CACHE_HOME=${build}/private-home/cache"
  "TMPDIR=${build}/tmp" LC_ALL=C HIP_VISIBLE_DEVICES=-1 ROCR_VISIBLE_DEVICES=-1 CUDA_VISIBLE_DEVICES=-1)
# Mirror the previous verifier's compiler/provider environment isolation.
execute_process(COMMAND "${CMAKE_COMMAND}" -E environment OUTPUT_VARIABLE current_environment)
string(REPLACE "\n" ";" environment_lines "${current_environment}")
foreach(line IN LISTS environment_lines)
  if(line MATCHES "^((GUFO_|DS4_)[A-Za-z0-9_]+)=")
    list(INSERT child_env 3 "--unset=${CMAKE_MATCH_1}")
  endif()
endforeach()
unset(current_environment)
unset(environment_lines)
function(run_recorded label)
  execute_process(COMMAND ${child_env} ${ARGN} WORKING_DIRECTORY "${LIE_SOURCE_ROOT}"
    OUTPUT_FILE "${out}/${label}.log" ERROR_FILE "${out}/${label}.log"
    TIMEOUT 5400 RESULT_VARIABLE result)
  set(command "[]")
  set(index 0)
  foreach(argument IN LISTS ARGN)
    lie_json_quote(quoted "${argument}")
    string(JSON command SET "${command}" ${index} "${quoted}")
    math(EXPR index "${index}+1")
  endforeach()
  set(row "{}")
  string(JSON row SET "${row}" argv "${command}")
  if(result MATCHES "^[0-9]+$")
    string(JSON row SET "${row}" exit_code "${result}")
  else()
    lie_json_quote(quoted "${result}")
    string(JSON row SET "${row}" failure "${quoted}")
  endif()
  string(JSON count LENGTH "${receipt}" commands)
  string(JSON receipt SET "${receipt}" commands ${count} "${row}")
  if(NOT result STREQUAL "0")
    string(JSON receipt SET "${receipt}" state "\"FAILED\"")
  endif()
  file(WRITE "${out}/result.json" "${receipt}\n")
  set(receipt "${receipt}" PARENT_SCOPE)
  if(NOT result STREQUAL "0")
    message(FATAL_ERROR "${label} failed (${result}); logs retained under ${out}")
  endif()
endfunction()
run_recorded(configure "${CMAKE_COMMAND}" -S "${LIE_SOURCE_ROOT}/cmake/gufo-runtime" -B "${build}" -G Ninja
  "-DGUFO_SOURCE=${source}" -DCMAKE_BUILD_TYPE=RelWithDebInfo -DBUILD_TESTING=OFF
  -DGUFO_BUILD_TOOLS=OFF -DENGINE_ENABLE_HIP=ON "-DCMAKE_HIP_ARCHITECTURES=${LIE_HIP_ARCHITECTURE}"
  "-DLIE_HIP_ARCHITECTURE=${LIE_HIP_ARCHITECTURE}"
  "-DLIE_C17_SAMPLING=${LIE_C17_SAMPLING}"
  "-DLIE_VISION_WEIGHT_DECODE=${LIE_VISION_WEIGHT_DECODE}"
  "-DLIE_DIRECTIONAL_STEERING=${LIE_DIRECTIONAL_STEERING}"
  "-DCMAKE_CXX_FLAGS=-include chrono" "-DCMAKE_HIP_FLAGS=-include chrono" "-DGUFO_REVISION=${LIE_GUFO_PIN}")
run_recorded(build "${CMAKE_COMMAND}" --build "${build}" --target gufo_qwen38_flash_next --parallel 1)
lie_verify_files("${source}" "${files}")
set(libraries "{}")
foreach(name IN ITEMS libgufo_core.a src/models/qwen38_flash_next/libgufo_qwen38_flash_next.a src/models/qwen38_flash_next/libgufo_qwen38_flash_next_mmq.a)
  file(SHA256 "${build}/${name}" hash)
  string(JSON libraries SET "${libraries}" "${name}" "\"${hash}\"")
endforeach()
string(JSON receipt SET "${receipt}" libraries "${libraries}")
foreach(pair IN ITEMS "source_manifest_sha256|third_party/gufo-source.json" "subset_cmake_sha256|cmake/gufo-runtime/CMakeLists.txt")
  string(REPLACE "|" ";" parts "${pair}")
  list(GET parts 0 field)
  list(GET parts 1 name)
  file(SHA256 "${LIE_SOURCE_ROOT}/${name}" hash)
  string(JSON receipt SET "${receipt}" "${field}" "\"${hash}\"")
endforeach()
file(SHA256 "${build}/CMakeCache.txt" hash)
string(JSON receipt SET "${receipt}" cmake_cache_sha256 "\"${hash}\"")
if(LIE_C17_SAMPLING)
  string(JSON receipt SET "${receipt}" c17_sampling true)
else()
  string(JSON receipt SET "${receipt}" c17_sampling false)
endif()
set(owned_sampling "{}")
foreach(name IN ITEMS src/sampling.c include/lie/sampling.h adapters/gufo_sampling.hpp src/sampling_history.c include/lie/sampling_history.h adapters/gufo_history.hpp src/sampling_distribution.c include/lie/sampling_distribution.h adapters/gufo_distribution.hpp src/grammar.c include/lie/grammar.h adapters/gufo_grammar.hpp)
  file(SHA256 "${LIE_SOURCE_ROOT}/${name}" hash)
  string(JSON owned_sampling SET "${owned_sampling}" "${name}" "\"${hash}\"")
endforeach()
string(JSON receipt SET "${receipt}" owned_sampling_files "${owned_sampling}")
if(LIE_VISION_WEIGHT_DECODE)
  string(JSON receipt SET "${receipt}" vision_weight_decode true)
else()
  string(JSON receipt SET "${receipt}" vision_weight_decode false)
endif()
set(owned_weights "{}")
foreach(name IN ITEMS src/weight_decode.c include/lie/weight_decode.h)
  file(SHA256 "${LIE_SOURCE_ROOT}/${name}" hash)
  string(JSON owned_weights SET "${owned_weights}" "${name}" "\"${hash}\"")
endforeach()
string(JSON receipt SET "${receipt}" owned_weight_decode_files "${owned_weights}")
if(LIE_DIRECTIONAL_STEERING)
  string(JSON receipt SET "${receipt}" directional_steering true)
else()
  string(JSON receipt SET "${receipt}" directional_steering false)
endif()
set(owned_steering "{}")
foreach(name IN ITEMS src/steering_activation.c include/lie/steering_activation.h adapters/hip/steering.hpp adapters/hip/steering.hip)
  file(SHA256 "${LIE_SOURCE_ROOT}/${name}" hash)
  string(JSON owned_steering SET "${owned_steering}" "${name}" "\"${hash}\"")
endforeach()
string(JSON receipt SET "${receipt}" owned_steering_files "${owned_steering}")
if(LIE_GUFO_STATE_ACCESS)
  file(SHA256 "${LIE_SOURCE_ROOT}/adapters/gufo-state/steering-edits.json" hash)
  string(JSON receipt SET "${receipt}" steering_edits_sha256 "\"${hash}\"")
  file(SHA256 "${LIE_SOURCE_ROOT}/adapters/gufo-state/vision-weight-edits.json" hash)
  string(JSON receipt SET "${receipt}" vision_weight_edits_sha256 "\"${hash}\"")
  file(SHA256 "${LIE_SOURCE_ROOT}/adapters/gufo-state/dense-sampling-edits.json" hash)
  string(JSON receipt SET "${receipt}" dense_sampling_edits_sha256 "\"${hash}\"")
  file(SHA256 "${LIE_SOURCE_ROOT}/adapters/gufo-state/history-sampling-edits.json" hash)
  string(JSON receipt SET "${receipt}" history_sampling_edits_sha256 "\"${hash}\"")
  file(SHA256 "${LIE_SOURCE_ROOT}/adapters/gufo-state/distribution-sampling-edits.json" hash)
  string(JSON receipt SET "${receipt}" distribution_sampling_edits_sha256 "\"${hash}\"")
  file(SHA256 "${LIE_SOURCE_ROOT}/adapters/gufo-state/grammar-runtime-edits.json" hash)
  string(JSON receipt SET "${receipt}" grammar_runtime_edits_sha256 "\"${hash}\"")
  file(SHA256 "${LIE_SOURCE_ROOT}/adapters/gufo-state/sampling-edits.json" hash)
  string(JSON receipt SET "${receipt}" sampling_edits_sha256 "\"${hash}\"")
  set(variant lie-state-access-v1)
  if(LIE_DS4_RUNTIME_CACHE)
    set(variant lie-ds4-state-v1)
    file(SHA256 "${LIE_SOURCE_ROOT}/adapters/gufo-state/kvc-edits.json" hash)
    string(JSON receipt SET "${receipt}" kvc_edits_sha256 "\"${hash}\"")
  endif()
  file(SHA256 "${LIE_SOURCE_ROOT}/adapters/gufo-state/access-edits.json" hash)
  string(JSON receipt SET "${receipt}" state_access_edits_sha256 "\"${hash}\"")
  string(JSON receipt SET "${receipt}" source_variant "\"${variant}\"")
  string(JSON receipt SET "${receipt}" variant_files "${files}")
endif()
string(JSON receipt SET "${receipt}" state "\"LIBRARIES_BUILT_NOT_EXECUTED_NOT_INFERENCE_QUALIFIED\"")
file(WRITE "${build}/BUILD-RECEIPT.json" "${receipt}\n")
file(WRITE "${out}/result.json" "${receipt}\n")
message(STATUS "Provider libraries built and verified; no inference execution")
