# SPDX-License-Identifier: MIT
cmake_minimum_required(VERSION 3.21)
include("${CMAKE_CURRENT_LIST_DIR}/Source.cmake")
set(destination "${LIE_SOURCE_ROOT}/.deps/gufo-f783fedb")
if(EXISTS "${destination}")
  message(FATAL_ERROR "Destination exists; refusing replacement: ${destination}")
endif()
file(READ "${LIE_SOURCE_ROOT}/third_party/gufo-source.json" manifest)
string(JSON url GET "${manifest}" url)
string(JSON expected GET "${manifest}" archive_sha256)
string(JSON files GET "${manifest}" files)
if(NOT expected STREQUAL "4b61a3f23e5ab51f7c95d6a7b6d2d82c8f7976e39f9566196f75323ab5eb2110")
  message(FATAL_ERROR "Unexpected archive pin")
endif()
set(stage "${LIE_SOURCE_ROOT}/.deps/gufo-fetch-stage")
if(EXISTS "${stage}")
  message(FATAL_ERROR "Fetch stage exists; preserve it and choose a clean checkout")
endif()
file(MAKE_DIRECTORY "${stage}")
file(DOWNLOAD "${url}" "${stage}/source.tar.gz" TLS_VERIFY ON TIMEOUT 60 STATUS status LOG log)
file(WRITE "${stage}/download.log" "${status}\n${log}")
list(GET status 0 code)
if(NOT code EQUAL 0)
  message(FATAL_ERROR "Source download failed; see ${stage}/download.log")
endif()
file(SIZE "${stage}/source.tar.gz" bytes)
file(SHA256 "${stage}/source.tar.gz" actual)
file(WRITE "${stage}/identity.txt" "expected=${expected}\nactual=${actual}\nbytes=${bytes}\n")
if(bytes GREATER 16000000 OR NOT actual STREQUAL expected)
  message(FATAL_ERROR "Pinned archive mismatch; download and identity retained")
endif()
execute_process(COMMAND "${CMAKE_COMMAND}" -E tar tf "${stage}/source.tar.gz"
  OUTPUT_VARIABLE names RESULT_VARIABLE code)
if(NOT code EQUAL 0)
  message(FATAL_ERROR "Cannot inspect source archive")
endif()
string(REGEX MATCH "^[^/\n]+" archive_root "${names}")
if(NOT archive_root STREQUAL "gufo-${LIE_GUFO_PIN}" AND NOT archive_root STREQUAL "gufo-org-gufo-f783fed")
  message(FATAL_ERROR "Unexpected source archive root")
endif()
# The committed per-file inventory selects regular source files only, excluding
# the two upstream editor symlinks. Verify before publishing the destination.
string(JSON count LENGTH "${files}")
math(EXPR last "${count}-1")
set(patterns)
foreach(i RANGE 0 ${last})
  string(JSON name MEMBER "${files}" ${i})
  list(APPEND patterns "${archive_root}/${name}")
endforeach()
file(ARCHIVE_EXTRACT INPUT "${stage}/source.tar.gz" DESTINATION "${stage}/unpack" PATTERNS ${patterns})
lie_verify_files("${stage}/unpack/${archive_root}" "${files}")
file(RENAME "${stage}/unpack/${archive_root}" "${destination}")
message(STATUS "Pinned sources ready: ${destination}; no build or model download")
