# SPDX-License-Identifier: MIT
include_guard(GLOBAL)
get_filename_component(LIE_SOURCE_ROOT "${CMAKE_CURRENT_LIST_DIR}/../.." ABSOLUTE)
set(LIE_GUFO_PIN f783fedb9bea2ec7de941f6da4e02f4a4596b29e)

function(lie_json_quote out value)
  string(REPLACE "\\" "\\\\" value "${value}")
  string(REPLACE "\"" "\\\"" value "${value}")
  string(REPLACE "\n" "\\n" value "${value}")
  string(REPLACE "\r" "\\r" value "${value}")
  string(REPLACE "\t" "\\t" value "${value}")
  set(${out} "\"${value}\"" PARENT_SCOPE)
endfunction()

function(lie_safe_file root name out)
  if(IS_ABSOLUTE "${name}" OR "${name}" MATCHES "(^|/)\\.\\.(/|$)" OR "${name}" MATCHES "[;\n\r]")
    message(FATAL_ERROR "Unsafe manifest path: ${name}")
  endif()
  file(REAL_PATH "${root}" base)
  file(REAL_PATH "${root}/${name}" resolved)
  string(FIND "${resolved}" "${base}/" inside)
  if(NOT inside EQUAL 0 OR IS_SYMLINK "${root}/${name}" OR NOT EXISTS "${resolved}" OR IS_DIRECTORY "${resolved}")
    message(FATAL_ERROR "Missing, linked or escaping source file: ${name}")
  endif()
  set(${out} "${resolved}" PARENT_SCOPE)
endfunction()

function(lie_verify_files root files)
  string(JSON count LENGTH "${files}")
  math(EXPR last "${count}-1")
  foreach(i RANGE 0 ${last})
    string(JSON name MEMBER "${files}" ${i})
    string(JSON expected GET "${files}" "${name}")
    lie_safe_file("${root}" "${name}" path)
    file(SHA256 "${path}" actual)
    if(NOT actual STREQUAL expected)
      message(FATAL_ERROR "Source/archive drift: ${name}")
    endif()
  endforeach()
endfunction()

# Derive exact variant hashes from the independently pinned pristine source.
# Every replacement must occur exactly once; no fuzzy patching is permitted.
function(lie_variant_files state_access kvc out_files out_changed)
  file(READ "${LIE_SOURCE_ROOT}/third_party/gufo-source.json" manifest)
  string(JSON pin GET "${manifest}" commit)
  if(NOT pin STREQUAL LIE_GUFO_PIN)
    message(FATAL_ERROR "Unexpected Gufo source pin")
  endif()
  string(JSON files GET "${manifest}" files)
  set(changed "{}")
  if(state_access)
    set(manifests access-edits.json)
    if(kvc)
      list(APPEND manifests kvc-edits.json)
    endif()
    foreach(edit_manifest IN LISTS manifests)
      file(READ "${LIE_SOURCE_ROOT}/adapters/gufo-state/${edit_manifest}" edits)
      string(JSON edit_pin GET "${edits}" source_pin)
      if(NOT edit_pin STREQUAL LIE_GUFO_PIN)
        message(FATAL_ERROR "State edit pin mismatch")
      endif()
      string(JSON count LENGTH "${edits}" edits)
      math(EXPR last "${count}-1")
      foreach(i RANGE 0 ${last})
        string(JSON name GET "${edits}" edits ${i} path)
        string(JSON old GET "${edits}" edits ${i} old)
        string(JSON new GET "${edits}" edits ${i} new)
        string(JSON content ERROR_VARIABLE absent GET "${changed}" "${name}")
        if(absent)
          lie_safe_file("${LIE_SOURCE_ROOT}/.deps/gufo-f783fedb" "${name}" source)
          file(SHA256 "${source}" actual)
          string(JSON expected GET "${files}" "${name}")
          if(NOT actual STREQUAL expected)
            message(FATAL_ERROR "Pristine source drift: ${name}")
          endif()
          file(READ "${source}" content)
        endif()
        string(FIND "${content}" "${old}" first)
        string(LENGTH "${old}" old_len)
        if(first LESS 0 OR old_len EQUAL 0)
          message(FATAL_ERROR "State replacement missing: ${name}")
        endif()
        math(EXPR after "${first}+${old_len}")
        string(SUBSTRING "${content}" ${after} -1 tail)
        string(FIND "${tail}" "${old}" duplicate)
        if(NOT duplicate EQUAL -1)
          message(FATAL_ERROR "State replacement is ambiguous: ${name}")
        endif()
        string(REPLACE "${old}" "${new}" content "${content}")
        string(SHA256 hash "${content}")
        string(JSON files SET "${files}" "${name}" "\"${hash}\"")
        lie_json_quote(quoted "${content}")
        string(JSON changed SET "${changed}" "${name}" "${quoted}")
      endforeach()
    endforeach()
  endif()
  set(${out_files} "${files}" PARENT_SCOPE)
  set(${out_changed} "${changed}" PARENT_SCOPE)
endfunction()
