# SPDX-License-Identifier: MIT
# The provider archives must have one recorded target matching the actual GPU.
function(lie_verify_hip_target build target)
  if(NOT target MATCHES "^gfx115[01]$")
    message(FATAL_ERROR "Unsupported HIP target ${target}")
  endif()
  file(READ "${build}/BUILD-RECEIPT.json" receipt)
  string(JSON recorded ERROR_VARIABLE absent GET "${receipt}" hip_architecture)
  if(absent OR NOT recorded STREQUAL target)
    message(FATAL_ERROR "Provider HIP target receipt mismatch")
  endif()
  string(JSON policy_hash ERROR_VARIABLE hash_absent GET "${receipt}" hip_target_cmake_sha256)
  file(SHA256 "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../hip-target.cmake" expected_hash)
  if(hash_absent OR NOT policy_hash STREQUAL expected_hash)
    message(FATAL_ERROR "HIP target policy drift; create a new private build")
  endif()
  file(STRINGS "${build}/CMakeCache.txt" hip_rows REGEX "^(CMAKE_HIP_ARCHITECTURES|LIE_HIP_ARCHITECTURE):")
  list(LENGTH hip_rows row_count)
  if(NOT row_count EQUAL 2)
    message(FATAL_ERROR "Provider HIP target cache is incomplete")
  endif()
  foreach(row IN LISTS hip_rows)
    if(NOT row MATCHES "^[A-Z_]+:[A-Z]+=${target}$")
      message(FATAL_ERROR "Provider HIP target cache mismatch")
    endif()
  endforeach()
endfunction()
