# SPDX-License-Identifier: MIT
cmake_minimum_required(VERSION 3.21)
include("${CMAKE_CURRENT_LIST_DIR}/Source.cmake")
function(lie_verify_gufo source build state_access kvc)
  file(REAL_PATH "${source}" source)
  file(REAL_PATH "${build}" build)
  foreach(pair IN ITEMS source build)
    if(pair STREQUAL "source")
      set(parent "${LIE_SOURCE_ROOT}/.deps/")
    else()
      set(parent "${LIE_SOURCE_ROOT}/build/")
    endif()
    string(FIND "${${pair}}/" "${parent}" inside)
    if(NOT inside EQUAL 0)
      message(FATAL_ERROR "Provider ${pair} must remain inside this repository")
    endif()
  endforeach()
  file(READ "${build}/BUILD-RECEIPT.json" receipt)
  string(JSON state GET "${receipt}" state)
  string(JSON pin GET "${receipt}" source_pin)
  string(JSON manifest_hash GET "${receipt}" source_manifest_sha256)
  file(SHA256 "${LIE_SOURCE_ROOT}/third_party/gufo-source.json" expected_hash)
  if(NOT state STREQUAL "LIBRARIES_BUILT_NOT_EXECUTED_NOT_INFERENCE_QUALIFIED" OR
     NOT pin STREQUAL LIE_GUFO_PIN OR NOT manifest_hash STREQUAL expected_hash)
    message(FATAL_ERROR "Provider build/source identity mismatch")
  endif()
  lie_variant_files("${state_access}" "${kvc}" files changed)
  string(JSON variant ERROR_VARIABLE absent GET "${receipt}" source_variant)
  string(JSON enabled ERROR_VARIABLE owned_absent GET "${receipt}" c17_sampling)
  if(state_access OR NOT owned_absent)
    if(NOT DEFINED LIE_C17_SAMPLING)
      set(LIE_C17_SAMPLING ON)
    endif()
    if(owned_absent)
      message(FATAL_ERROR "Owned sampling build identity missing")
    endif()
    if((enabled AND NOT LIE_C17_SAMPLING) OR (LIE_C17_SAMPLING AND NOT enabled))
      message(FATAL_ERROR "Owned sampling build selection mismatch")
    endif()
    string(JSON owned_sampling GET "${receipt}" owned_sampling_files)
    string(JSON owned_count LENGTH "${owned_sampling}")
    if(NOT owned_count EQUAL 120)
      message(FATAL_ERROR "Owned sampling file inventory mismatch")
    endif()
    foreach(name IN ITEMS src/sampling.c include/lie/sampling.h adapters/gufo_sampling.hpp src/sampling_history.c include/lie/sampling_history.h adapters/gufo_history.hpp src/sampling_storage.c include/lie/sampling_storage.h adapters/gufo_sampling_storage.hpp src/sampling_distribution.c include/lie/sampling_distribution.h adapters/gufo_distribution.hpp src/grammar.c include/lie/grammar.h adapters/gufo_grammar.hpp src/grammar_number.c include/lie/grammar_number.h adapters/gufo_grammar_number.hpp src/grammar_regex.c include/lie/grammar_regex.h adapters/gufo_grammar_regex.hpp src/grammar_string.c include/lie/grammar_string.h adapters/gufo_grammar_string.hpp src/grammar_vocabulary.c include/lie/grammar_vocabulary.h adapters/gufo_grammar_vocabulary.hpp src/grammar_regex_compile.c include/lie/grammar_regex_compile.h adapters/gufo_grammar_regex_compile.hpp src/grammar_regex_parse.c include/lie/grammar_regex_parse.h adapters/gufo_grammar_regex_parse.hpp src/grammar_unicode.c include/lie/grammar_unicode.h src/grammar_builder.c include/lie/grammar_builder.h adapters/gufo_grammar_builder.hpp src/schema_transform.c include/lie/schema_transform.h adapters/gufo_schema_transform.hpp src/schema_internal.h src/schema_values.c include/lie/schema_values.h adapters/gufo_schema_values.hpp src/grammar_cache.c include/lie/grammar_cache.h adapters/gufo_grammar_cache.hpp src/schema_memo.c include/lie/schema_memo.h adapters/gufo_schema_memo.hpp src/schema_dispatch.c include/lie/schema_dispatch.h adapters/gufo_schema_dispatch.hpp src/schema_visit.c include/lie/schema_visit.h adapters/gufo_schema_visit.hpp src/schema_root.c include/lie/schema_root.h adapters/gufo_schema_root.hpp src/schema_compile.c include/lie/schema_compile.h adapters/gufo_schema_compile.hpp src/schema_compiler.c include/lie/schema_compiler.h adapters/gufo_schema_compiler.hpp src/schema_arena.c include/lie/schema_arena.h adapters/gufo_schema_arena.hpp src/schema_string.c include/lie/schema_string.h adapters/gufo_schema_string.hpp src/schema_frontend.c include/lie/schema_frontend.h adapters/gufo_schema_frontend.hpp src/schema_body.c include/lie/schema_body.h adapters/gufo_schema_body.hpp src/schema_number.c include/lie/schema_number.h adapters/gufo_schema_number.hpp src/schema_integer.c include/lie/schema_integer.h adapters/gufo_schema_integer.hpp src/schema_format.c include/lie/schema_format.h adapters/gufo_schema_format.hpp src/ordered_cache.c include/lie/ordered_cache.h adapters/gufo_composition_cache.hpp src/grammar_composition.c include/lie/grammar_composition.h adapters/gufo_grammar_composition.hpp src/binary64.c include/lie/binary64.h src/json_parse.c include/lie/json_parse.h adapters/gufo_json_parse.hpp src/json_value.c include/lie/json_value.h adapters/gufo_json_value.hpp src/json_store.c include/lie/json_store.h adapters/gufo_schema_store.hpp src/grammar_lexeme.c include/lie/grammar_lexeme.h adapters/gufo_grammar_lexeme.hpp adapters/gufo_grammar_state.hpp third_party/ryu-source.json third_party/ryu/LICENSE-Apache2 third_party/ryu/LICENSE-Boost third_party/ryu/ryu/d2s.c third_party/ryu/ryu/s2d.c third_party/ryu/ryu/ryu.h third_party/ryu/ryu/ryu_parse.h third_party/ryu/ryu/common.h third_party/ryu/ryu/digit_table.h third_party/ryu/ryu/d2s_intrinsics.h third_party/ryu/ryu/d2s_full_table.h third_party/ryu/ryu/d2s_small_table.h)
      string(JSON hash GET "${owned_sampling}" "${name}")
    endforeach()
    lie_verify_files("${LIE_SOURCE_ROOT}" "${owned_sampling}")
  endif()
  if(NOT DEFINED LIE_VISION_WEIGHT_DECODE)
    set(LIE_VISION_WEIGHT_DECODE ON)
  endif()
  string(JSON weights_enabled GET "${receipt}" vision_weight_decode)
  if((weights_enabled AND NOT LIE_VISION_WEIGHT_DECODE) OR
     (LIE_VISION_WEIGHT_DECODE AND NOT weights_enabled))
    message(FATAL_ERROR "Vision weight decode build selection mismatch")
  endif()
  string(JSON owned_weights GET "${receipt}" owned_weight_decode_files)
  string(JSON owned_weights_count LENGTH "${owned_weights}")
  if(NOT owned_weights_count EQUAL 2)
    message(FATAL_ERROR "Owned weight decode inventory mismatch")
  endif()
  foreach(name IN ITEMS src/weight_decode.c include/lie/weight_decode.h)
    string(JSON hash GET "${owned_weights}" "${name}")
  endforeach()
  lie_verify_files("${LIE_SOURCE_ROOT}" "${owned_weights}")
  if(NOT DEFINED LIE_ATTENTION_DISPATCH_STATS)
    set(LIE_ATTENTION_DISPATCH_STATS ON)
  endif()
  string(JSON dispatch_enabled ERROR_VARIABLE dispatch_absent GET "${receipt}" attention_dispatch_stats)
  if(dispatch_absent)
    message(FATAL_ERROR "Attention dispatch build identity missing; rebuild explicitly")
  endif()
  string(JSON dispatch_type TYPE "${receipt}" attention_dispatch_stats)
  if(NOT dispatch_type STREQUAL "BOOLEAN")
    message(FATAL_ERROR "Attention dispatch build identity must be boolean")
  endif()
  if((dispatch_enabled AND NOT LIE_ATTENTION_DISPATCH_STATS) OR
     (LIE_ATTENTION_DISPATCH_STATS AND NOT dispatch_enabled))
    message(FATAL_ERROR "Attention dispatch build selection mismatch")
  endif()
  string(JSON owned_dispatch GET "${receipt}" owned_dispatch_files)
  if(NOT DEFINED LIE_LONG_CONTEXT_WMMA)
    set(LIE_LONG_CONTEXT_WMMA ON)
  endif()
  string(JSON long_enabled ERROR_VARIABLE long_absent GET "${receipt}" long_context_wmma)
  if(long_absent)
    message(FATAL_ERROR "Long-context WMMA build identity missing; rebuild explicitly")
  endif()
  string(JSON long_type TYPE "${receipt}" long_context_wmma)
  if(NOT long_type STREQUAL "BOOLEAN")
    message(FATAL_ERROR "Long-context WMMA build identity must be boolean")
  endif()
  if((long_enabled AND NOT LIE_LONG_CONTEXT_WMMA) OR
     (LIE_LONG_CONTEXT_WMMA AND NOT long_enabled))
    message(FATAL_ERROR "Long-context WMMA build selection mismatch")
  endif()
  if(long_enabled AND NOT state_access)
    message(FATAL_ERROR "Long-context WMMA requires the verified owned source variant")
  endif()
  string(JSON dispatch_count LENGTH "${owned_dispatch}")
  if(NOT dispatch_count EQUAL 2)
    message(FATAL_ERROR "Owned dispatch file inventory mismatch")
  endif()
  foreach(name IN ITEMS src/dispatch.c include/lie/dispatch.h)
    string(JSON hash GET "${owned_dispatch}" "${name}")
  endforeach()
  lie_verify_files("${LIE_SOURCE_ROOT}" "${owned_dispatch}")
  if(state_access)
    file(SHA256 "${LIE_SOURCE_ROOT}/adapters/gufo-state/attention-dispatch-edits.json" hash)
    string(JSON expected GET "${receipt}" attention_dispatch_edits_sha256)
    if(NOT hash STREQUAL expected)
      message(FATAL_ERROR "Attention dispatch edit provenance mismatch")
    endif()
  endif()
  if(NOT DEFINED LIE_DIRECTIONAL_STEERING)
    set(LIE_DIRECTIONAL_STEERING ON)
  endif()
  string(JSON steering_enabled ERROR_VARIABLE steering_absent GET "${receipt}" directional_steering)
  if(steering_absent)
    message(FATAL_ERROR "Directional steering build identity missing; rebuild explicitly")
  endif()
  if((steering_enabled AND NOT LIE_DIRECTIONAL_STEERING) OR
     (LIE_DIRECTIONAL_STEERING AND NOT steering_enabled))
    message(FATAL_ERROR "Directional steering build selection mismatch")
  endif()
  if(steering_enabled AND NOT state_access)
    message(FATAL_ERROR "Directional steering requires the verified state-access variant")
  endif()
  string(JSON owned_steering GET "${receipt}" owned_steering_files)
  string(JSON steering_count LENGTH "${owned_steering}")
  if(NOT steering_count EQUAL 4)
    message(FATAL_ERROR "Owned steering file inventory mismatch")
  endif()
  foreach(name IN ITEMS src/steering_activation.c include/lie/steering_activation.h adapters/hip/steering.hpp adapters/hip/steering.hip)
    string(JSON hash GET "${owned_steering}" "${name}")
  endforeach()
  lie_verify_files("${LIE_SOURCE_ROOT}" "${owned_steering}")
  if(state_access)
    file(SHA256 "${LIE_SOURCE_ROOT}/adapters/gufo-state/steering-edits.json" hash)
    string(JSON expected GET "${receipt}" steering_edits_sha256)
    if(NOT hash STREQUAL expected)
      message(FATAL_ERROR "Steering edit provenance mismatch")
    endif()
    file(SHA256 "${LIE_SOURCE_ROOT}/adapters/gufo-state/vision-weight-edits.json" hash)
    string(JSON expected GET "${receipt}" vision_weight_edits_sha256)
    if(NOT hash STREQUAL expected)
      message(FATAL_ERROR "Vision weight edit provenance mismatch")
    endif()
    file(SHA256 "${LIE_SOURCE_ROOT}/adapters/gufo-state/dense-sampling-edits.json" hash)
    string(JSON expected GET "${receipt}" dense_sampling_edits_sha256)
    if(NOT hash STREQUAL expected)
      message(FATAL_ERROR "Owned sampling edit provenance mismatch")
    endif()
    file(SHA256 "${LIE_SOURCE_ROOT}/adapters/gufo-state/history-sampling-edits.json" hash)
    string(JSON expected GET "${receipt}" history_sampling_edits_sha256)
    if(NOT hash STREQUAL expected)
      message(FATAL_ERROR "Owned history edit provenance mismatch")
    endif()
    file(SHA256 "${LIE_SOURCE_ROOT}/adapters/gufo-state/distribution-sampling-edits.json" hash)
    string(JSON expected GET "${receipt}" distribution_sampling_edits_sha256)
    if(NOT hash STREQUAL expected)
      message(FATAL_ERROR "Owned distribution edit provenance mismatch")
    endif()
    file(SHA256 "${LIE_SOURCE_ROOT}/adapters/gufo-state/sampling-storage-edits.json" hash)
    string(JSON expected GET "${receipt}" sampling_storage_edits_sha256)
    if(NOT hash STREQUAL expected)
      message(FATAL_ERROR "Owned sampling storage edit provenance mismatch")
    endif()
    file(SHA256 "${LIE_SOURCE_ROOT}/adapters/gufo-state/grammar-runtime-edits.json" hash)
    string(JSON expected GET "${receipt}" grammar_runtime_edits_sha256)
    if(NOT hash STREQUAL expected)
      message(FATAL_ERROR "Owned grammar runtime edit provenance mismatch")
    endif()
    file(SHA256 "${LIE_SOURCE_ROOT}/adapters/gufo-state/schema-integer-edits.json" hash)
    string(JSON expected GET "${receipt}" schema_integer_edits_sha256)
    if(NOT hash STREQUAL expected)
      message(FATAL_ERROR "Owned schema integer edit provenance mismatch")
    endif()
    file(SHA256 "${LIE_SOURCE_ROOT}/adapters/gufo-state/schema-compile-edits.json" hash)
    string(JSON expected GET "${receipt}" schema_compile_edits_sha256)
    if(NOT hash STREQUAL expected)
      message(FATAL_ERROR "Owned schema compilation edit provenance mismatch")
    endif()
    file(SHA256 "${LIE_SOURCE_ROOT}/adapters/gufo-state/schema-store-edits.json" hash)
    string(JSON expected GET "${receipt}" schema_store_edits_sha256)
    if(NOT hash STREQUAL expected)
      message(FATAL_ERROR "Owned schema store edit provenance mismatch")
    endif()
    file(SHA256 "${LIE_SOURCE_ROOT}/adapters/gufo-state/grammar-storage-edits.json" hash)
    string(JSON expected GET "${receipt}" grammar_storage_edits_sha256)
    if(NOT hash STREQUAL expected)
      message(FATAL_ERROR "Owned grammar storage edit provenance mismatch")
    endif()
    file(SHA256 "${LIE_SOURCE_ROOT}/adapters/gufo-state/schema-root-edits.json" hash)
    string(JSON expected GET "${receipt}" schema_root_edits_sha256)
    if(NOT hash STREQUAL expected)
      message(FATAL_ERROR "Owned schema root edit provenance mismatch")
    endif()
    file(SHA256 "${LIE_SOURCE_ROOT}/adapters/gufo-state/schema-visit-edits.json" hash)
    string(JSON expected GET "${receipt}" schema_visit_edits_sha256)
    if(NOT hash STREQUAL expected)
      message(FATAL_ERROR "Owned schema visit edit provenance mismatch")
    endif()
    file(SHA256 "${LIE_SOURCE_ROOT}/adapters/gufo-state/schema-body-edits.json" hash)
    string(JSON expected GET "${receipt}" schema_body_edits_sha256)
    if(NOT hash STREQUAL expected)
      message(FATAL_ERROR "Owned schema body edit provenance mismatch")
    endif()
    file(SHA256 "${LIE_SOURCE_ROOT}/adapters/gufo-state/binary64-edits.json" hash)
    string(JSON expected GET "${receipt}" binary64_edits_sha256)
    if(NOT hash STREQUAL expected)
      message(FATAL_ERROR "Owned binary64 edit provenance mismatch")
    endif()
    file(SHA256 "${LIE_SOURCE_ROOT}/adapters/gufo-state/json-parser-edits.json" hash)
    string(JSON expected GET "${receipt}" json_parser_edits_sha256)
    if(NOT hash STREQUAL expected)
      message(FATAL_ERROR "Owned JSON parser edit provenance mismatch")
    endif()
    file(SHA256 "${LIE_SOURCE_ROOT}/adapters/gufo-state/grammar-lexeme-edits.json" hash)
    string(JSON expected GET "${receipt}" grammar_lexeme_edits_sha256)
    if(NOT hash STREQUAL expected)
      message(FATAL_ERROR "Owned grammar lexeme edit provenance mismatch")
    endif()
    file(SHA256 "${LIE_SOURCE_ROOT}/adapters/gufo-state/grammar-state-edits.json" hash)
    string(JSON expected GET "${receipt}" grammar_state_edits_sha256)
    if(NOT hash STREQUAL expected)
      message(FATAL_ERROR "Owned grammar state edit provenance mismatch")
    endif()
    file(SHA256 "${LIE_SOURCE_ROOT}/adapters/gufo-state/json-value-edits.json" hash)
    string(JSON expected GET "${receipt}" json_value_edits_sha256)
    if(NOT hash STREQUAL expected)
      message(FATAL_ERROR "Owned JSON value edit provenance mismatch")
    endif()
    file(SHA256 "${LIE_SOURCE_ROOT}/adapters/gufo-state/composition-edits.json" hash)
    string(JSON expected GET "${receipt}" composition_edits_sha256)
    if(NOT hash STREQUAL expected)
      message(FATAL_ERROR "Owned composition edit provenance mismatch")
    endif()
    file(SHA256 "${LIE_SOURCE_ROOT}/adapters/gufo-state/composition-cache-edits.json" hash)
    string(JSON expected GET "${receipt}" composition_cache_edits_sha256)
    if(NOT hash STREQUAL expected)
      message(FATAL_ERROR "Owned composition cache edit provenance mismatch")
    endif()
    file(SHA256 "${LIE_SOURCE_ROOT}/adapters/gufo-state/schema-format-edits.json" hash)
    string(JSON expected GET "${receipt}" schema_format_edits_sha256)
    if(NOT hash STREQUAL expected)
      message(FATAL_ERROR "Owned schema format edit provenance mismatch")
    endif()
    file(SHA256 "${LIE_SOURCE_ROOT}/adapters/gufo-state/schema-dispatch-edits.json" hash)
    string(JSON expected GET "${receipt}" schema_dispatch_edits_sha256)
    if(NOT hash STREQUAL expected)
      message(FATAL_ERROR "Owned schema dispatch edit provenance mismatch")
    endif()
    file(SHA256 "${LIE_SOURCE_ROOT}/adapters/gufo-state/schema-memo-edits.json" hash)
    string(JSON expected GET "${receipt}" schema_memo_edits_sha256)
    if(NOT hash STREQUAL expected)
      message(FATAL_ERROR "Owned schema memo edit provenance mismatch")
    endif()
    file(SHA256 "${LIE_SOURCE_ROOT}/adapters/gufo-state/grammar-cache-edits.json" hash)
    string(JSON expected GET "${receipt}" grammar_cache_edits_sha256)
    if(NOT hash STREQUAL expected)
      message(FATAL_ERROR "Owned grammar cache edit provenance mismatch")
    endif()
    file(SHA256 "${LIE_SOURCE_ROOT}/adapters/gufo-state/schema-values-edits.json" hash)
    string(JSON expected GET "${receipt}" schema_values_edits_sha256)
    if(NOT hash STREQUAL expected)
      message(FATAL_ERROR "Owned schema value edit provenance mismatch")
    endif()
    file(SHA256 "${LIE_SOURCE_ROOT}/adapters/gufo-state/schema-transform-edits.json" hash)
    string(JSON expected GET "${receipt}" schema_transform_edits_sha256)
    if(NOT hash STREQUAL expected)
      message(FATAL_ERROR "Owned schema transformation edit provenance mismatch")
    endif()
    file(SHA256 "${LIE_SOURCE_ROOT}/adapters/gufo-state/grammar-number-edits.json" hash)
    string(JSON expected GET "${receipt}" grammar_number_edits_sha256)
    if(NOT hash STREQUAL expected)
      message(FATAL_ERROR "Owned grammar number edit provenance mismatch")
    endif()
    file(SHA256 "${LIE_SOURCE_ROOT}/adapters/gufo-state/grammar-regex-edits.json" hash)
    string(JSON expected GET "${receipt}" grammar_regex_edits_sha256)
    if(NOT hash STREQUAL expected)
      message(FATAL_ERROR "Owned grammar regex edit provenance mismatch")
    endif()
    file(SHA256 "${LIE_SOURCE_ROOT}/adapters/gufo-state/grammar-parser-edits.json" hash)
    string(JSON expected GET "${receipt}" grammar_parser_edits_sha256)
    if(NOT hash STREQUAL expected)
      message(FATAL_ERROR "Owned grammar parser edit provenance mismatch")
    endif()
    file(SHA256 "${LIE_SOURCE_ROOT}/adapters/gufo-state/grammar-compiler-edits.json" hash)
    string(JSON expected GET "${receipt}" grammar_compiler_edits_sha256)
    if(NOT hash STREQUAL expected)
      message(FATAL_ERROR "Owned regex compiler edit provenance mismatch")
    endif()
    file(SHA256 "${LIE_SOURCE_ROOT}/adapters/gufo-state/grammar-vocabulary-edits.json" hash)
    string(JSON expected GET "${receipt}" grammar_vocabulary_edits_sha256)
    if(NOT hash STREQUAL expected)
      message(FATAL_ERROR "Owned grammar vocabulary edit provenance mismatch")
    endif()
    file(SHA256 "${LIE_SOURCE_ROOT}/adapters/gufo-state/grammar-string-edits.json" hash)
    string(JSON expected GET "${receipt}" grammar_string_edits_sha256)
    if(NOT hash STREQUAL expected)
      message(FATAL_ERROR "Owned grammar string edit provenance mismatch")
    endif()
    set(expected_variant lie-state-access-v1)
    if(kvc)
      set(expected_variant lie-ds4-state-v1)
    endif()
    if(absent OR NOT variant STREQUAL expected_variant)
      message(FATAL_ERROR "Provider variant requires explicit matching selection")
    endif()
    file(SHA256 "${LIE_SOURCE_ROOT}/adapters/gufo-state/sampling-edits.json" hash)
    string(JSON expected GET "${receipt}" sampling_edits_sha256)
    if(NOT hash STREQUAL expected)
      message(FATAL_ERROR "Sampling edit provenance mismatch")
    endif()
    file(SHA256 "${LIE_SOURCE_ROOT}/adapters/gufo-state/access-edits.json" hash)
    string(JSON expected GET "${receipt}" state_access_edits_sha256)
    if(NOT hash STREQUAL expected)
      message(FATAL_ERROR "State access edit manifest drift")
    endif()
    if(kvc)
      file(SHA256 "${LIE_SOURCE_ROOT}/adapters/gufo-state/kvc-edits.json" hash)
      string(JSON expected GET "${receipt}" kvc_edits_sha256)
      if(NOT hash STREQUAL expected)
        message(FATAL_ERROR "KVC edit manifest drift")
      endif()
    endif()
    string(JSON recorded GET "${receipt}" variant_files)
    string(JSON equal EQUAL "${files}" "${recorded}")
    if(NOT equal)
      message(FATAL_ERROR "Variant file inventory mismatch")
    endif()
  elseif(NOT absent)
    message(FATAL_ERROR "Modified provider requires state access selection")
  endif()
  lie_verify_files("${source}" "${files}")
  string(JSON libraries GET "${receipt}" libraries)
  string(JSON count LENGTH "${libraries}")
  if(NOT count EQUAL 3)
    message(FATAL_ERROR "Unexpected provider library count")
  endif()
  foreach(name IN ITEMS libgufo_core.a src/models/qwen38_flash_next/libgufo_qwen38_flash_next.a src/models/qwen38_flash_next/libgufo_qwen38_flash_next_mmq.a)
    string(JSON hash GET "${libraries}" "${name}")
  endforeach()
  lie_verify_files("${build}" "${libraries}")
  file(SHA256 "${build}/CMakeCache.txt" hash)
  string(JSON expected GET "${receipt}" cmake_cache_sha256)
  if(NOT hash STREQUAL expected)
    message(FATAL_ERROR "Provider CMake cache drift")
  endif()
  string(JSON scope GET "${receipt}" scope)
  if(scope STREQUAL "lie-qwen-only-source-subset")
    file(SHA256 "${LIE_SOURCE_ROOT}/cmake/gufo-runtime/CMakeLists.txt" hash)
    string(JSON expected GET "${receipt}" subset_cmake_sha256)
    if(NOT hash STREQUAL expected)
      message(FATAL_ERROR "Provider build recipe drift")
    endif()
  endif()
  message(STATUS "Verified pinned Gufo sources and archives; no inference qualification")
endfunction()
if(CMAKE_SCRIPT_MODE_FILE STREQUAL CMAKE_CURRENT_LIST_FILE)
  lie_verify_gufo("${GUFO_SOURCE}" "${GUFO_BUILD}" "${LIE_GUFO_STATE_ACCESS}" "${LIE_DS4_RUNTIME_CACHE}")
endif()
