# SPDX-License-Identifier: MIT
cmake_minimum_required(VERSION 3.21)
include("${CMAKE_CURRENT_LIST_DIR}/Source.cmake")
function(lie_verify_gufo source build state_access kvc)
  file(REAL_PATH "${source}" source)
  file(REAL_PATH "${build}" build)
  foreach(pair IN ITEMS source build)
    if(pair STREQUAL "source")
      set(parent "${LIE_SOURCE_ROOT}/.deps/")
    else()
      set(parent "${LIE_SOURCE_ROOT}/build/")
    endif()
    string(FIND "${${pair}}/" "${parent}" inside)
    if(NOT inside EQUAL 0)
      message(FATAL_ERROR "Provider ${pair} must remain inside this repository")
    endif()
  endforeach()
  file(READ "${build}/BUILD-RECEIPT.json" receipt)
  string(JSON state GET "${receipt}" state)
  string(JSON pin GET "${receipt}" source_pin)
  string(JSON manifest_hash GET "${receipt}" source_manifest_sha256)
  file(SHA256 "${LIE_SOURCE_ROOT}/third_party/gufo-source.json" expected_hash)
  if(NOT state STREQUAL "LIBRARIES_BUILT_NOT_EXECUTED_NOT_INFERENCE_QUALIFIED" OR
     NOT pin STREQUAL LIE_GUFO_PIN OR NOT manifest_hash STREQUAL expected_hash)
    message(FATAL_ERROR "Provider build/source identity mismatch")
  endif()
  lie_variant_files("${state_access}" "${kvc}" files changed)
  string(JSON variant ERROR_VARIABLE absent GET "${receipt}" source_variant)
  string(JSON enabled ERROR_VARIABLE owned_absent GET "${receipt}" c17_sampling)
  if(state_access OR NOT owned_absent)
    if(NOT DEFINED LIE_C17_SAMPLING)
      set(LIE_C17_SAMPLING ON)
    endif()
    if(owned_absent)
      message(FATAL_ERROR "Owned sampling build identity missing")
    endif()
    if((enabled AND NOT LIE_C17_SAMPLING) OR (LIE_C17_SAMPLING AND NOT enabled))
      message(FATAL_ERROR "Owned sampling build selection mismatch")
    endif()
    string(JSON owned_sampling GET "${receipt}" owned_sampling_files)
    string(JSON owned_count LENGTH "${owned_sampling}")
    if(NOT owned_count EQUAL 3)
      message(FATAL_ERROR "Owned sampling file inventory mismatch")
    endif()
    foreach(name IN ITEMS src/sampling.c include/lie/sampling.h adapters/gufo_sampling.hpp)
      string(JSON hash GET "${owned_sampling}" "${name}")
    endforeach()
    lie_verify_files("${LIE_SOURCE_ROOT}" "${owned_sampling}")
  endif()
  if(state_access)
    file(SHA256 "${LIE_SOURCE_ROOT}/adapters/gufo-state/dense-sampling-edits.json" hash)
    string(JSON expected GET "${receipt}" dense_sampling_edits_sha256)
    if(NOT hash STREQUAL expected)
      message(FATAL_ERROR "Owned sampling edit provenance mismatch")
    endif()
    set(expected_variant lie-state-access-v1)
    if(kvc)
      set(expected_variant lie-ds4-state-v1)
    endif()
    if(absent OR NOT variant STREQUAL expected_variant)
      message(FATAL_ERROR "Provider variant requires explicit matching selection")
    endif()
    file(SHA256 "${LIE_SOURCE_ROOT}/adapters/gufo-state/sampling-edits.json" hash)
    string(JSON expected GET "${receipt}" sampling_edits_sha256)
    if(NOT hash STREQUAL expected)
      message(FATAL_ERROR "Sampling edit provenance mismatch")
    endif()
    file(SHA256 "${LIE_SOURCE_ROOT}/adapters/gufo-state/access-edits.json" hash)
    string(JSON expected GET "${receipt}" state_access_edits_sha256)
    if(NOT hash STREQUAL expected)
      message(FATAL_ERROR "State access edit manifest drift")
    endif()
    if(kvc)
      file(SHA256 "${LIE_SOURCE_ROOT}/adapters/gufo-state/kvc-edits.json" hash)
      string(JSON expected GET "${receipt}" kvc_edits_sha256)
      if(NOT hash STREQUAL expected)
        message(FATAL_ERROR "KVC edit manifest drift")
      endif()
    endif()
    string(JSON recorded GET "${receipt}" variant_files)
    string(JSON equal EQUAL "${files}" "${recorded}")
    if(NOT equal)
      message(FATAL_ERROR "Variant file inventory mismatch")
    endif()
  elseif(NOT absent)
    message(FATAL_ERROR "Modified provider requires state access selection")
  endif()
  lie_verify_files("${source}" "${files}")
  string(JSON libraries GET "${receipt}" libraries)
  string(JSON count LENGTH "${libraries}")
  if(NOT count EQUAL 3)
    message(FATAL_ERROR "Unexpected provider library count")
  endif()
  foreach(name IN ITEMS libgufo_core.a src/models/qwen38_flash_next/libgufo_qwen38_flash_next.a src/models/qwen38_flash_next/libgufo_qwen38_flash_next_mmq.a)
    string(JSON hash GET "${libraries}" "${name}")
  endforeach()
  lie_verify_files("${build}" "${libraries}")
  file(SHA256 "${build}/CMakeCache.txt" hash)
  string(JSON expected GET "${receipt}" cmake_cache_sha256)
  if(NOT hash STREQUAL expected)
    message(FATAL_ERROR "Provider CMake cache drift")
  endif()
  string(JSON scope GET "${receipt}" scope)
  if(scope STREQUAL "lie-qwen-only-source-subset")
    file(SHA256 "${LIE_SOURCE_ROOT}/cmake/gufo-runtime/CMakeLists.txt" hash)
    string(JSON expected GET "${receipt}" subset_cmake_sha256)
    if(NOT hash STREQUAL expected)
      message(FATAL_ERROR "Provider build recipe drift")
    endif()
  endif()
  message(STATUS "Verified pinned Gufo sources and archives; no inference qualification")
endfunction()
if(CMAKE_SCRIPT_MODE_FILE STREQUAL CMAKE_CURRENT_LIST_FILE)
  lie_verify_gufo("${GUFO_SOURCE}" "${GUFO_BUILD}" "${LIE_GUFO_STATE_ACCESS}" "${LIE_DS4_RUNTIME_CACHE}")
endif()
