# SPDX-License-Identifier: MIT
# Synapse LIE .161: operator-authorized 96 GiB GPU shared-memory limit.
# 25165824 pages * 4096 bytes; this maximum does not reserve RAM.
options ttm pages_limit=25165824
